In [1]:
import pandas as pd

In [2]:
tb1 = pd.read_csv('Wave 1x Daily PnL combined.csv')
tb2 = pd.read_csv('Wave 1x combined.csv')

In [7]:
tb1.tail()

,Trade No.,Portfolio,Date,Entry Price,Exit Price,Points,Qty,Slippage,PnL,ROI%,Index,Trade Year,Allocation,Qty apAlloc,PnL apAlloc,ROI% PF
4883,334,1000000,2024-11-26,80171.54,80005.93,-165.61,10,3.150969,-1687.609690,-0.168761,SENSEX,2024,250000.0,2.5,-421.902423,-0.042190
4884,334,1000000,2024-11-27,80005.93,80244.75,238.82,10,3.150969,2356.690310,0.235669,SENSEX,2024,250000.0,2.5,589.172578,0.058917
4885,334,1000000,2024-11-28,80244.75,79165.22,-1079.53,10,3.150969,-10826.809690,-1.082681,SENSEX,2024,250000.0,2.5,-2706.702422,-0.270670
4886,335,1000000,2024-11-29,79788.75,79747.12,-41.63,10,7.954938,-495.849384,-0.049585,SENSEX,2024,250000.0,2.5,-123.962346,-0.012396
4887,335,1000000,2024-12-02,79747.12,80253.78,506.66,10,7.954938,4987.050616,0.498705,SENSEX,2024,250000.0,2.5,1246.762654,0.124676

In [8]:
tb2.tail()

,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,...,ROI%,Trade Year,Trade Month,Index,Portfolio,Allocation,Qty apAlloc,PnL apAlloc,ROI% PF,Slippage
1791,2024-11-26 10:45:00,LONG,2024-11-26 11:15:00,52147.95,51365.73075,52147.210000,2024-11-27 09:15:00,52078.1000,-69.8500,-80.272605,...,-0.120409,2024,11,BANKNIFTY,1000000,250000.0,3.75,-301.022269,-0.030102,10.422605
1792,2024-11-27 10:15:00,LONG,2024-11-27 10:45:00,52146.95,51364.74575,52317.040000,2024-11-28 10:15:00,52239.1000,92.1500,81.711395,...,0.122567,2024,11,BANKNIFTY,1000000,250000.0,3.75,306.417731,0.030642,10.438605
1793,2024-11-28 11:15:00,LONG,2024-11-28 11:45:00,52183.60,51400.84600,51400.846000,2024-11-28 12:15:00,52085.9000,-97.7000,-108.126950,...,-0.162190,2024,11,BANKNIFTY,1000000,250000.0,3.75,-405.476062,-0.040548,10.426950
1794,2024-11-29 12:15:00,LONG,2024-11-29 13:15:00,79788.75,79310.01750,79310.017500,2024-12-02 09:15:00,79310.0175,-478.7325,-494.642377,...,-0.494642,2024,11,SENSEX,1000000,250000.0,2.50,-1236.605942,-0.123661,15.909877
1795,2024-12-03 09:15:00,LONG,2024-12-03 09:45:00,52487.25,51699.94125,53142.216667,2024-12-05 09:45:00,53032.6000,545.3500,534.798015,...,0.802197,2024,12,BANKNIFTY,1000000,250000.0,3.75,2005.492556,0.200549,10.551985

In [5]:
tb2['Slippage'] = tb2['Points Captured'] - tb2['After Costs']

In [6]:
tb1['Slippage'].sum() , tb2['Slippage'].sum()

(13170.906927167125, 13445.841204157125)