In [12]:
import pandas as pd
import polars as pl
pd.set_option("display.max_rows", 25_000)
pd.set_option("display.max_columns", 500)
pl.Config.set_tbl_cols(500)
pl.Config.set_tbl_rows(10_000)

pd.options.display.float_format = "{:.4f}".format

In [27]:
# molotov = pd.read_csv('molo.csv')
wave = pd.read_csv('Wave Tb.csv')
nlc = pd.read_csv('NLC_New_10m.csv')

In [28]:
nlc['ROI%'].sum()

535.6517383131231

In [29]:
# molotov['Strategy'] = 'MOLOTOV'
wave['Strategy'] = 'WAVE'
nlc['Strategy'] = 'NLC'

In [30]:
wave.head()

,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,PnL,Remarks,Qty,Leverage,ROI%,Trade Year,Trade Month,Index,Portfolio,Allocation,Qty apAlloc,PnL apAlloc,ROI% PF,Strategy
0,2017-01-02 12:15:00,LONG,2017-01-02 13:15:00,8166.5500,8112.6508,8223.0913,2017-01-09 14:15:00,8235.2000,68.6500,65.3697,55564.2025,MACD Reversal,850,7,5.5564,2017,1,NIFTY,1000000,500000.0000,425.0000,27782.1013,2.7782,WAVE
1,2017-01-02 12:15:00,LONG,2017-01-02 13:15:00,26540.5700,26381.3266,26381.3266,2017-01-09 15:15:00,26711.9600,171.3900,166.0647,49819.4241,MACD Reversal,300,8,4.9819,2017,1,SENSEX,1000000,500000.0000,150.0000,24909.7120,2.4910,WAVE
2,2017-01-10 10:15:00,LONG,2017-01-10 11:15:00,26863.6300,26702.4482,27177.2408,2017-01-20 10:15:00,27199.2400,335.6100,330.2037,99061.1139,MACD Reversal,300,8,9.9061,2017,1,SENSEX,1000000,500000.0000,150.0000,49530.5570,4.9531,WAVE
3,2017-01-10 12:15:00,LONG,2017-01-10 13:15:00,8274.9000,8220.2857,8410.5962,2017-01-20 10:15:00,8407.6000,132.7000,129.3635,109958.9750,TSL Hit,850,7,10.9959,2017,1,NIFTY,1000000,500000.0000,425.0000,54979.4875,5.4979,WAVE
4,2017-01-20 10:15:00,LONG,2017-01-20 11:15:00,8411.9000,8356.3815,8356.3815,2017-01-20 11:15:00,8413.1000,1.2000,-2.1650,-1786.1250,MACD Reversal,825,7,-0.1786,2017,1,NIFTY,1000000,500000.0000,412.5000,-893.0625,-0.0893,WAVE

In [31]:
nlc.head()

,Unnamed: 0,date,day,expiry,DTE,strike,type,Entry Price,Entry Time,initial sl,Exit Price,Exit date,Exit Time,RSI on Entry,Remark,Points Captured,Slippage,Qty,PnL,ROI%,Trade Year,Trade Month,Highest High,Lowest Low,Max ROI%,Margin,DATETIME,Cumulative ROI%,Max Cumulative ROI%,DD,Strategy
0,0,2019-01-25,Friday,2019-01-31,6,10900,C,49.8500,14:05:00,108.9500,0.0500,2019-01-31,15:25:00,0,EOD exit,49.8000,0.4990,507.6142,25025.8883,2.5026,2019,1,52.9000,0.0500,2.5279,69.1624,2019-01-25 14:05:00,2.5026,2.5026,0.0000,NLC
1,294,2019-02-12,Tuesday,2019-02-14,2,10850,P,24.1500,11:25:00,38.6000,38.6000,2019-02-12,14:35:00,0,SL hit,-14.4500,0.6275,1843.3180,-27792.6267,-2.7793,2019,2,44.0000,20.3500,0.7005,250.0000,2019-02-12 11:25:00,-0.2767,2.5026,-2.7793,NLC
2,1,2019-02-12,Tuesday,2019-02-14,2,10900,C,34.0000,14:35:00,62.1000,0.0500,2019-02-14,15:25:00,0,EOD exit,33.9500,0.3405,1067.6157,35882.0285,3.5882,2019,2,39.7000,0.0500,3.6246,145.4626,2019-02-12 14:35:00,3.3115,3.3115,0.0000,NLC
3,2,2019-02-18,Monday,2019-02-21,3,10750,C,41.0500,11:05:00,72.9000,35.0000,2019-02-21,15:25:00,0,EOD exit,6.0500,0.7605,941.9152,4982.2606,0.4982,2019,2,56.7500,5.8000,3.3203,126.5699,2019-02-18 11:05:00,3.8098,3.8098,0.0000,NLC
4,295,2019-02-25,Monday,2019-02-28,3,10800,P,46.4000,09:15:00,53.9500,53.9500,2019-02-25,09:25:00,0,SL hit,-7.5500,1.0035,1851.8519,-15839.8148,-1.5840,2019,2,55.3000,46.4000,0.0000,250.0000,2019-02-25 09:15:00,2.2258,3.8098,-1.5840,NLC

In [32]:
wave['Final ROI%'] = wave['ROI% PF']
nlc['Final ROI%'] = nlc['ROI%']
wave['DATETIME'] = wave['Entry Time']

In [33]:
combined_df = pd.concat([wave, nlc], ignore_index=True)
combined_df['DATETIME'] = pd.to_datetime(combined_df['DATETIME'])
combined_df = combined_df.sort_values(by='DATETIME', ignore_index=True)

In [34]:
# # combined_df.loc[combined_df['Trade Year'] < 2022, 'Portfolio'] = 30000000
# # combined_df.loc[combined_df['Trade Year'] >= 2022, 'Portfolio'] = 40000000
# combined_df['Portfolio'] = 2000000
# combined_df['Allocation'] = 1000000
# combined_df['ROI% PF'] = combined_df['PnL'] * 100 / combined_df['Portfolio']

In [35]:
combined_df.tail(10)

,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,PnL,Remarks,Qty,Leverage,ROI%,Trade Year,Trade Month,Index,Portfolio,Allocation,Qty apAlloc,PnL apAlloc,ROI% PF,Strategy,Final ROI%,DATETIME,Unnamed: 0,date,day,expiry,DTE,strike,type,initial sl,Exit date,RSI on Entry,Remark,Slippage,Highest High,Lowest Low,Max ROI%,Margin,Cumulative ROI%,Max Cumulative ROI%,DD
2434,NaN,NaN,10:15:00,233.1000,NaN,NaN,11:45:00,399.9000,-166.8000,NaN,-31138.4892,NaN,179.8561,NaN,-3.1138,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NLC,-3.1138,2025-01-21 10:15:00,291.0000,2025-01-21,Tuesday,2025-01-23,2.0000,23050.0000,C,399.9000,2025-01-21,0.0000,SL hit,6.3300,401.8000,219.0500,0.2527,51.8210,528.9447,537.8678,-8.9231
2435,NaN,NaN,12:15:00,139.0500,NaN,NaN,15:25:00,5.3500,133.7000,NaN,27775.1488,NaN,210.0105,NaN,2.7775,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NLC,2.7775,2025-01-21 12:15:00,292.0000,2025-01-21,Tuesday,2025-01-23,2.0000,23200.0000,C,281.9000,2025-01-23,0.0000,EOD exit,1.4440,212.2000,2.6000,2.8656,60.9030,531.7222,537.8678,-6.1456
2436,NaN,NaN,14:15:00,58.1500,NaN,NaN,15:25:00,0.0500,58.1000,NaN,21773.3754,NaN,378.5489,NaN,2.1773,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NLC,2.1773,2025-01-22 14:15:00,605.0000,2025-01-22,Wednesday,2025-01-23,1.0000,23100.0000,P,137.4000,2025-01-23,0.0000,EOD exit,0.5820,69.7000,0.0500,2.1994,109.3060,533.8995,537.8678,-3.9682
2437,2025-01-23 09:45:00,LONG,2025-01-23 10:15:00,48808.9000,48076.7665,48671.2567,2025-01-23 14:15:00,48597.9000,-211.0000,-220.7407,-23177.7714,TSL Hit,105.0000,5.0000,-2.3178,2025,1,BANKNIFTY,1000000.0000,250000.0000,26.2500,-5794.4429,-0.5794,WAVE,-0.5794,2025-01-23 10:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2438,2025-01-23 09:15:00,LONG,2025-01-23 10:15:00,12194.7500,12114.2646,12114.2646,2025-01-24 09:15:00,12114.2646,-80.4854,-92.6399,-60215.9073,Initial SL Hit,650.0000,8.0000,-6.0216,2025,1,MIDCPNIFTY,1000000.0000,250000.0000,162.5000,-15053.9768,-1.5054,WAVE,-1.5054,2025-01-23 10:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2439,2025-01-23 11:15:00,LONG,2025-01-23 12:15:00,23238.6000,23085.2252,23218.6075,2025-01-23 14:15:00,23202.5000,-36.1000,-45.3882,-13616.4660,TSL Hit,300.0000,7.0000,-1.3616,2025,1,NIFTY,1000000.0000,250000.0000,75.0000,-3404.1165,-0.3404,WAVE,-0.3404,2025-01-23 12:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2440,2025-01-23 15:15:00,LONG,2025-01-24 09:15:00,76561.7700,76102.3994,76102.3994,2025-01-24 09:15:00,76383.5100,-178.2600,-193.5545,-19355.4528,MACD Reversal,100.0000,8.0000,-1.9355,2025,1,SENSEX,1000000.0000,250000.0000,25.0000,-4838.8632,-0.4839,WAVE,-0.4839,2025-01-24 09:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2441,NaN,NaN,11:05:00,77.4000,NaN,NaN,14:35:00,165.2500,-87.8500,NaN,-30828.6283,NaN,341.4912,NaN,-3.0829,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NLC,-3.0829,2025-01-24 11:05:00,606.0000,2025-01-24,Friday,2025-01-30,6.0000,23050.0000,P,165.2500,2025-01-24,0.0000,SL hit,2.4265,169.8000,62.1500,0.5208,98.3921,530.8167,537.8678,-7.0511
2442,NaN,NaN,14:05:00,202.0500,NaN,NaN,15:25:00,149.6500,52.4000,NaN,9705.4269,NaN,198.5440,NaN,0.9705,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NLC,0.9705,2025-01-24 14:05:00,293.0000,2025-01-24,Friday,2025-01-30,6.0000,23100.0000,C,353.1500,2025-01-30,0.0000,EOD exit,3.5170,241.0000,52.0000,2.9792,57.3296,531.7872,537.8678,-6.0806
2443,NaN,NaN,11:55:00,172.3000,NaN,NaN,15:25:00,0.1500,172.1500,NaN,38645.2381,NaN,226.7574,NaN,3.8645,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NLC,3.8645,2025-01-28 11:55:00,607.0000,2025-01-28,Tuesday,2025-01-30,2.0000,23100.0000,P,304.6000,2025-01-30,0.0000,EOD exit,1.7245,235.5500,0.1000,3.9048,65.4762,535.6517,537.8678,-2.2160

In [45]:
combined_df.loc[combined_df['Strategy'] == 'NLC', 'Final ROI%'] *= 0.34
combined_df.loc[combined_df['Strategy'] == 'WAVE', 'Final ROI%'] *= 0.66

In [46]:
combined_df = combined_df[combined_df['Trade Year'] >= 2019]
combined_df.head(10)

,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,PnL,Remarks,Qty,Leverage,ROI%,Trade Year,Trade Month,Index,Portfolio,Allocation,Qty apAlloc,PnL apAlloc,ROI% PF,Strategy,Final ROI%,DATETIME,Unnamed: 0,date,day,expiry,DTE,strike,type,initial sl,Exit date,RSI on Entry,Remark,Slippage,Highest High,Lowest Low,Max ROI%,Margin,Cumulative ROI%,Max Cumulative ROI%,DD
305,2018-12-31 15:15:00,LONG,2019-01-01 09:15:00,27181.0000,26773.2850,26773.2850,2019-01-01 09:45:00,27070.7000,-110.3000,-115.7252,-20830.5306,MACD Reversal,180.0000,5.0000,-2.0831,2019,1,BANKNIFTY,1000000.0000,333333.0000,59.9999,-6943.5033,-0.6944,WAVE,-0.2291,2019-01-01 09:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,2019-01-01 14:15:00,LONG,2019-01-01 14:45:00,27309.4500,26899.8082,27253.2300,2019-01-02 12:15:00,27220.5000,-88.9500,-94.4030,-16992.5391,TSL Hit,180.0000,5.0000,-1.6993,2019,1,BANKNIFTY,1000000.0000,333333.0000,59.9999,-5664.1740,-0.5664,WAVE,-0.1869,2019-01-01 14:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,2019-01-01 14:15:00,LONG,2019-01-01 15:15:00,36266.6700,36049.0700,36049.0700,2019-01-02 09:15:00,36049.0700,-217.6000,-224.8316,-49462.9507,Initial SL hit,220.0000,8.0000,-4.9463,2019,1,SENSEX,1000000.0000,333333.0000,73.3333,-16487.6337,-1.6488,WAVE,-0.5441,2019-01-01 15:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,2019-01-01 14:15:00,LONG,2019-01-01 15:15:00,10913.8500,10841.8186,10841.8186,2019-01-02 09:15:00,10841.8186,-72.0314,-76.3825,-49648.6534,Initial SL hit,650.0000,7.0000,-4.9649,2019,1,NIFTY,1000000.0000,333333.0000,216.6664,-16549.5346,-1.6550,WAVE,-0.5461,2019-01-01 15:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,2019-01-02 09:15:00,LONG,2019-01-02 10:15:00,36203.1200,35985.9013,35985.9013,2019-01-02 12:15:00,35985.9013,-217.2187,-224.4376,-49376.2769,Initial SL hit,220.0000,8.0000,-4.9376,2019,1,SENSEX,1000000.0000,333333.0000,73.3333,-16458.7425,-1.6459,WAVE,-0.5431,2019-01-02 10:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,2019-01-02 09:15:00,LONG,2019-01-02 10:15:00,10882.8500,10811.0232,10811.0232,2019-01-02 12:15:00,10811.0232,-71.8268,-76.1656,-49507.6300,Initial SL hit,650.0000,7.0000,-4.9508,2019,1,NIFTY,1000000.0000,333333.0000,216.6664,-16502.5268,-1.6503,WAVE,-0.5446,2019-01-02 10:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,2019-01-04 11:45:00,LONG,2019-01-04 12:15:00,27158.0000,26750.6300,27372.1600,2019-01-07 14:45:00,27305.8500,147.8500,142.4036,25632.6507,TSL Hit,180.0000,5.0000,2.5633,2019,1,BANKNIFTY,1000000.0000,333333.0000,59.9999,8544.2084,0.8544,WAVE,0.2820,2019-01-04 12:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,2019-01-07 09:15:00,LONG,2019-01-07 10:15:00,10822.4500,10751.0218,10791.3388,2019-01-07 14:15:00,10751.0218,-71.4282,-75.7429,-49232.8618,Initial SL hit,650.0000,7.0000,-4.9233,2019,1,NIFTY,1000000.0000,333333.0000,216.6664,-16410.9375,-1.6411,WAVE,-0.5416,2019-01-07 10:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2019-01-07 12:15:00,LONG,2019-01-07 13:15:00,35968.6000,35752.7884,35885.9980,2019-01-07 14:15:00,35863.1900,-105.4100,-112.5932,-24770.4994,TSL Hit,220.0000,8.0000,-2.4770,2019,1,SENSEX,1000000.0000,333333.0000,73.3333,-8256.8249,-0.8257,WAVE,-0.2725,2019-01-07 13:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2019-01-07 15:15:00,LONG,2019-01-08 09:15:00,10778.9500,10707.8089,10784.6388,2019-01-11 11:15:00,10775.6500,-3.3000,-7.6109,-4947.0980,TSL Hit,650.0000,7.0000,-0.4947,2019,1,NIFTY,1000000.0000,333333.0000,216.6664,-1649.0310,-0.1649,WAVE,-0.0544,2019-01-08 09:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
def generate_stats(tb_expiry, variation):
    stats_df8 = pd.DataFrame(
        index=range(2019, 2026),
        columns=[
            "Total ROI",
            "Total Trades",
            "Win Rate",
            "Avg Profit% per Trade",
            "Avg Loss% per Trade",
            "Max Drawdown",
            "ROI/DD Ratio",
            "Variation",
        ],
    )
    combined_df_sorted = tb_expiry
    # combined_df_sorted = tb_expiry_ce
    # combined_df_sorted = tb_expiry_pe
    
    # Iterate over each year
    for year in range(2019, 2026):
        # Filter trades for the current year
        year_trades = combined_df_sorted[(combined_df_sorted["Trade Year"] == year)]
    
        # Calculate total ROI
        total_roi = year_trades["Final ROI%"].sum()
    
        # Calculate total number of trades
        total_trades = len(year_trades)
    
        # Calculate win rate
        win_rate = (year_trades["Final ROI%"] > 0).mean() * 100
    
        # Calculate average profit per trade
        avg_profit = year_trades[year_trades["Final ROI%"] > 0]["Final ROI%"].mean()
    
        # Calculate average loss per trade
        avg_loss = year_trades[year_trades["Final ROI%"] < 0]["Final ROI%"].mean()
    
        # Calculate maximum drawdown
        max_drawdown = (
            year_trades["Final ROI%"].cumsum() - year_trades["Final ROI%"].cumsum().cummax()
        ).min()
    
        # Calculate ROI/DD ratio
        roi_dd_ratio = total_roi / abs(max_drawdown)

        variation = variation
    
        # Store the statistics in the DataFrame
        stats_df8.loc[year] = [
            total_roi,
            total_trades,
            win_rate,
            avg_profit,
            avg_loss,
            max_drawdown,
            roi_dd_ratio,
            variation,
        ]
    
    # Calculate overall statistics
    overall_total_roi = stats_df8["Total ROI"].sum()
    overall_total_trades = stats_df8["Total Trades"].sum()
    overall_win_rate = (combined_df_sorted["Final ROI%"] > 0).mean() * 100
    overall_avg_profit = combined_df_sorted[combined_df_sorted["Final ROI%"] > 0]["Final ROI%"].mean()
    overall_avg_loss = combined_df_sorted[combined_df_sorted["Final ROI%"] < 0]["Final ROI%"].mean()
    overall_max_drawdown = (
        combined_df_sorted["Final ROI%"].cumsum() - combined_df_sorted["Final ROI%"].cumsum().cummax()
    ).min()
    overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)
    overall_variation = variation
    
    # Store the overall statistics in the DataFrame
    stats_df8.loc["Overall"] = [
        overall_total_roi,
        overall_total_trades,
        overall_win_rate,
        overall_avg_profit,
        overall_avg_loss,
        overall_max_drawdown,
        overall_roi_dd_ratio,
        overall_variation,
    ]
    return {overall_roi_dd_ratio : stats_df8}

In [48]:
stats = generate_stats(combined_df, 'NLC + WAVE 1:2 Alloc')

In [44]:
# combined_df['ROI% PF'] = combined_df['Final ROI%']
stats = generate_stats(combined_df, 'NLC + WAVE 1:2 Alloc')
for x, y in stats.items():
    z = pd.DataFrame(y)

z

,Total ROI,Total Trades,Win Rate,Avg Profit% per Trade,Avg Loss% per Trade,Max Drawdown,ROI/DD Ratio,Variation
2019,77.0433,317,39.7476,1.5219,-0.6006,-14.6493,5.2592,NLC + WAVE 50-50 Alloc
2020,197.8760,325,44.3077,2.5340,-0.9227,-13.8475,14.2897,NLC + WAVE 50-50 Alloc
2021,115.9094,328,42.9878,1.8094,-0.7445,-23.7685,4.8766,NLC + WAVE 50-50 Alloc
2022,92.1720,380,41.0526,1.6026,-0.7046,-23.1945,3.9739,NLC + WAVE 50-50 Alloc
2023,80.6393,387,40.3101,1.3034,-0.5311,-12.1045,6.6619,NLC + WAVE 50-50 Alloc
2024,83.9909,370,44.0541,1.2602,-0.5866,-11.8924,7.0626,NLC + WAVE 50-50 Alloc
2025,-1.8486,32,37.5000,1.0233,-0.7064,-7.1526,-0.2585,NLC + WAVE 50-50 Alloc
Overall,645.7823,2139,41.9822,1.6513,-0.6745,-23.7685,27.1696,NLC + WAVE 50-50 Alloc

In [18]:
combined_df.tail(50)

,date,day,expiry,DTE,strike,type,Entry Price,Entry Time,initial sl,TSL,...,Highest High,Lowest Low,Max ROI%,Margin,Strategy,Unnamed: 0,RSI on Entry,Portfolio,Allocation,ROI% PF
1420,2024-05-13,Monday,2024-05-16,3,22000,P,83.65,13:45:00,251.00,NaN,...,87.35,0.05,1.498656,49.297879,NLC,550.0,0.0,2000000,1000000,0.741826
1421,2024-05-13,Monday,2024-05-16,3,22050,C,105.00,09:15:00,160.00,NaN,...,174.85,54.60,2.749091,150.340909,NLC,259.0,0.0,2000000,1000000,-1.572273
1422,2024-05-15,Wednesday,2024-05-16,1,22300,C,34.35,10:30:00,86.50,0.0000,...,121.05,0.75,1.288591,106.903164,MOLOTOV,NaN,NaN,2000000,1000000,-1.023174
1423,2024-05-17,Friday,2024-05-23,6,22400,P,115.75,11:05:00,173.45,NaN,...,130.90,0.05,6.015598,145.580589,NLC,551.0,0.0,2000000,1000000,2.977695
1424,2024-05-17,Friday,2024-05-23,6,22400,P,110.80,12:40:00,173.45,0.5575,...,127.80,0.05,3.535515,89.385475,MOLOTOV,NaN,NaN,2000000,1000000,1.750064
1425,2024-05-18,Saturday,2024-05-23,5,22550,C,96.05,11:50:00,105.85,0.0000,...,121.45,69.95,1.851885,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,-0.419299
1426,2024-05-21,Tuesday,2024-05-23,2,22450,C,125.95,10:10:00,182.10,0.0000,...,182.80,114.30,0.414960,99.955476,MOLOTOV,NaN,NaN,2000000,1000000,-1.054862
1427,2024-05-21,Tuesday,2024-05-23,2,22450,C,116.00,10:35:00,182.10,NaN,...,182.80,114.30,0.077156,127.363843,NLC,260.0,0.0,2000000,1000000,-1.567648
1428,2024-05-22,Wednesday,2024-05-23,1,22600,C,65.00,09:20:00,77.20,0.0000,...,79.95,46.15,1.334513,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,-0.482195
1429,2024-05-22,Wednesday,2024-05-23,1,22550,C,85.50,11:35:00,108.00,0.0000,...,109.50,78.60,0.489579,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,-0.866874
1430,2024-05-24,Friday,2024-05-30,6,22900,P,95.25,12:55:00,155.00,NaN,...,171.60,46.55,2.445188,143.723849,NLC,552.0,0.0,2000000,1000000,-1.562824
1431,2024-05-24,Friday,2024-05-30,6,22900,P,114.55,12:30:00,155.00,118.7475,...,171.60,46.55,3.362176,141.532756,MOLOTOV,NaN,NaN,2000000,1000000,-1.066638
1432,2024-05-27,Monday,2024-05-30,3,23050,C,112.50,14:45:00,214.85,NaN,...,119.75,0.05,3.296043,84.452858,NLC,261.0,0.0,2000000,1000000,1.631527
1433,2024-05-27,Monday,2024-05-30,3,23050,C,130.75,09:25:00,152.20,0.0000,...,158.95,116.40,0.996095,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,-0.842672
1434,2024-05-28,Tuesday,2024-05-30,2,23000,C,135.25,10:30:00,144.90,0.0000,...,140.70,0.05,9.405217,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,4.655548
1435,2024-05-28,Tuesday,2024-05-30,2,23000,C,130.15,09:30:00,139.00,0.0000,...,144.90,107.20,1.596522,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,-0.401443
1436,2024-05-28,Tuesday,2024-05-30,2,23000,C,125.50,09:20:00,137.60,0.0000,...,139.00,125.25,0.017391,200.000000,MOLOTOV,NaN,NaN,2000000,1000000,-0.512383
1437,2024-05-29,Wednesday,2024-05-30,1,22750,P,68.25,13:25:00,120.60,86.3925,...,140.80,60.30,0.303725,108.643744,MOLOTOV,NaN,NaN,2000000,1000000,-1.036074
1438,2024-05-31,Friday,2024-06-06,6,22600,C,357.50,12:35:00,451.95,0.0000,...,454.20,351.25,0.132345,59.820011,MOLOTOV,NaN,NaN,2000000,1000000,-1.085701
1439,2024-05-31,Friday,2024-06-06,6,22550,P,367.05,13:35:00,500.00,154.7025,...,561.50,50.00,4.769462,42.403159,MOLOTOV,NaN,NaN,2000000,1000000,-1.065216
1440,2024-06-04,Tuesday,2024-06-06,2,23200,C,210.95,09:50:00,265.90,0.0000,...,245.25,0.05,7.676069,105.550500,MOLOTOV,NaN,NaN,2000000,1000000,3.799636
1441,2024-06-04,Tuesday,2024-06-06,2,22450,P,797.30,15:05:00,1395.50,1.0550,...,903.30,0.05,2.665496,9.382314,MOLOTOV,NaN,NaN,2000000,1000000,1.319419
1442,2024-06-06,Thursday,2024-06-06,0,22750,P,112.00,09:25:00,243.95,NaN,...,160.55,0.05,2.545282,64.655172,NLC,553.0,0.0,2000000,1000000,1.259903
1443,2024-06-07,Friday,2024-06-13,6,22800,P,97.75,12:30:00,219.70,0.1675,...,105.65,0.05,1.602296,46.740467,MOLOTOV,NaN,NaN,2000000,1000000,0.793128
1444,2024-06-07,Friday,2024-06-13,6,22800,P,117.20,11:05:00,219.70,NaN,...,128.50,0.05,3.428780,83.414634,NLC,554.0,0.0,2000000,1000000,1.697232
1445,2024-06-10,Monday,2024-06-13,3,23350,C,120.30,14:25:00,231.00,NaN,...,167.80,27.10,2.525745,79.098916,NLC,262.0,0.0,2000000,1000000,0.943184
1446,2024-06-14,Friday,2024-06-20,6,23450,P,110.30,14:45:00,196.85,NaN,...,117.90,0.05,3.821490,101.603120,NLC,555.0,0.0,2000000,1000000,1.891620
1447,2024-06-19,Wednesday,2024-06-20,1,23650,C,26.55,10:15:00,60.80,NaN,...,82.55,18.35,0.693446,250.000000,NLC,263.0,0.0,2000000,1000000,-1.485137
1448,2024-06-20,Thursday,2024-06-20,0,23600,C,22.20,09:45:00,49.20,NaN,...,58.00,8.85,1.131356,250.000000,NLC,264.0,0.0,2000000,1000000,-1.174322
1449,2024-06-21,Friday,2024-06-27,6,23700,C,51.35,12:35:00,101.45,NaN,...,109.70,21.30,1.799401,177.395210,NLC,265.0,0.0,2000000,1000000,-1.545749
1450,2024-06-25,Tuesday,2024-06-27,2,23550,P,86.05,09:35:00,112.15,NaN,...,96.60,0.05,7.303609,250.000000,NLC,556.0,0.0,2000000,1000000,3.615244
1451,2024-07-01,Monday,2024-07-04,3,23950,P,68.80,11:15:00,113.00,NaN,...,70.80,0.05,4.666290,203.195701,NLC,557.0,0.0,2000000,1000000,2.309779
1452,2024-07-02,Tuesday,2024-07-04,2,24250,C,55.35,12:35:00,96.15,NaN,...,99.50,40.95,1.058824,222.886029,NLC,266.0,0.0,2000000,1000000,-1.555699
1453,2024-07-09,Tuesday,2024-07-11,2,24350,P,86.10,09:15:00,114.85,NaN,...,142.65,32.55,4.398357,250.000000,NLC,558.0,0.0,2000000,1000000,-1.263224
1454,2024-07-10,Wednesday,2024-07-11,1,24500,C,27.15,10:05:00,59.80,NaN,...,27.65,0.05,2.212245,250.000000,NLC,267.0,0.0,2000000,1000000,1.095020
1455,2024-07-15,Monday,2024-07-18,3,24550,P,82.45,10:35:00,119.30,NaN,...,95.20,0.05,6.708277,249.830393,NLC,559.0,0.0,2000000,1000000,3.320556
1456,2024-07-16,Tuesday,2024-07-18,2,24650,C,52.80,14:25:00,104.90,NaN,...,109.50,8.80,2.533589,177.423225,NLC,268.0,0.0,2000000,1000000,-1.545403
1457,2024-07-19,Friday,2024-07-25,6,24900,C,98.20,14:05:00,184.90,NaN,...,106.90,0.05,3.396194,107.698962,NLC,269.0,0.0,2000000,1000000,1.681099
1458,2024-07-29,Monday,2024-08-01,3,24900,P,70.20,11:25:00,139.00,NaN,...,165.60,66.90,0.143895,135.719477,NLC,560.0,0.0,2000000,1000000,-1.545610
1459,2024-07-31,Wednesday,2024-08-01,1,24850,P,42.50,14:15:00,91.00,NaN,...,49.85,0.05,2.625773,192.139175,NLC,561.0,0.0,2000000,1000000,1.299727
1460,2024-08-02,Friday,2024-08-08,6,24800,C,113.85,14:25:00,175.00,NaN,...,115.30,0.05,5.582993,152.085037,NLC,270.0,0.0,2000000,1000000,2.763557
1461,2024-08-20,Tuesday,2024-08-22,2,24600,P,89.05,09:15:00,108.25,NaN,...,95.70,0.05,7.235772,250.000000,NLC,562.0,0.0,2000000,1000000,3.581667
1462,2024-08-23,Friday,2024-08-29,6,24800,P,86.50,14:15:00,141.50,NaN,...,117.55,0.05,4.715455,169.090909,NLC,563.0,0.0,2000000,1000000,2.328614
1463,2024-08-30,Friday,2024-09-05,6,25200,P,96.45,11:05:00,128.00,NaN,...,156.00,43.70,4.186508,250.000000,NLC,564.0,0.0,2000000,1000000,-1.928214
1464,2024-09-02,Monday,2024-09-05,3,25350,C,70.35,12:35:00,117.95,NaN,...,79.40,0.05,4.430672,199.711134,NLC,271.0,0.0,2000000,1000000,2.193151
1465,2024-09-13,Friday,2024-09-19,6,25400,P,141.00,11:05:00,219.60,NaN,...,193.95,0.05,5.379771,121.183206,NLC,565.0,0.0,2000000,1000000,2.662968
1466,2024-09-17,Tuesday,2024-09-19,2,25450,C,66.20,09:45:00,88.65,NaN,...,93.00,61.75,0.349705,250.000000,NLC,272.0,0.0,2000000,1000000,-0.942967
1467,2024-09-23,Monday,2024-09-26,3,25850,P,100.80,13:25:00,148.20,NaN,...,103.65,0.10,6.373418,204.509494,NLC,566.0,0.0,2000000,1000000,3.151582
1468,2024-09-25,Wednesday,2024-09-26,1,25900,C,101.00,09:15:00,107.25,NaN,...,109.30,90.20,0.833977,250.000000,NLC,273.0,0.0,2000000,1000000,-0.321718
1469,2024-09-25,Wednesday,2024-09-26,1,25950,C,60.30,11:35:00,89.90,NaN,...,92.00,50.00,0.793834,250.000000,NLC,274.0,0.0,2000000,1000000,-1.198536