In [5]:
import pandas as pd

df = pd.read_csv('finalised/BNF_5LS_final.csv')
df

,Date,Position,Type,Expiry,Index,Contract,Entry Time,Exit Time,Entry Price,Exit Price,Quantity,PnL,Points,ROI
0,2017-01-05,CLOSED,HEDGE,2017-01-05,BANKNIFTY,17700PE,09:16:00,15:22:00,1.10,0.05,847.457627,-889.830508,-1.05,-0.088983
1,2017-01-05,CLOSED,HEDGE,2017-01-05,BANKNIFTY,18300CE,09:16:00,15:22:00,2.30,0.05,819.672131,-1844.262295,-2.25,-0.184426
2,2017-01-05,CLOSED,STRADDLE,2017-01-05,BANKNIFTY,17800CE,09:16:00,13:56:00,200.00,302.65,-168.539326,-17300.561800,-102.65,-1.730056
3,2017-01-05,CLOSED,STRADDLE,2017-01-05,BANKNIFTY,17800PE,09:16:00,13:56:00,4.95,0.10,-168.539326,817.415730,4.85,0.081742
4,2017-01-05,CLOSED,STRADDLE,2017-01-05,BANKNIFTY,17900CE,09:16:00,15:22:00,117.65,195.00,-167.597765,-12963.687150,-77.35,-1.296369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7203,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46300PE,13:59:00,15:22:00,21.30,0.30,-64.794816,1360.691145,21.00,0.136069
7204,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46200CE,14:12:00,15:22:00,149.90,119.65,-64.935065,1964.285714,30.25,0.196429
7205,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46200PE,14:12:00,15:22:00,28.80,0.15,-64.935065,1860.389610,28.65,0.186039
7206,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46100CE,14:24:00,15:22:00,162.95,218.80,-65.075922,-3634.490239,-55.85,-0.363449
7207,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46100PE,14:24:00,15:22:00,25.05,0.10,-65.075922,1623.644252,24.95,0.162364

In [2]:
import pandas as pd
df['Date'] = pd.to_datetime(df['Date'])
df['PnL_w_cs'] = df['PnL'] - (0.001 * df['Quantity'] * -1 * (df['Entry Price'] + df['Exit Price']))
df['ROI_w_cs'] = df['PnL_w_cs'] / 10000
daily_pnl = df.groupby(df['Date'].dt.date)['PnL_w_cs'].sum().reset_index()

# Rename the columns for clarity
daily_pnl.columns = ['Date', 'Total PnL']

daily_pnl["Date"] = pd.to_datetime(daily_pnl["Date"])
daily_pnl['Trade Year'] = daily_pnl['Date'].dt.year
daily_pnl["ROI"] = daily_pnl["Total PnL"]/10000
# If you want to ensure 'Date' column is in datetime format
daily_pnl['Date'] = pd.to_datetime(daily_pnl['Date'])

# Display the resulting DataFrame
print(daily_pnl)

          Date      Total PnL  Trade Year        ROI
0   2017-01-05   12008.858903        2017   1.200886
1   2017-01-12    4506.671221        2017   0.450667
2   2017-01-19   28947.604379        2017   2.894760
3   2017-01-25 -120578.586132        2017 -12.057859
4   2017-02-02   14133.974243        2017   1.413397
..         ...            ...         ...        ...
360 2024-02-21   12736.490774        2024   1.273649
361 2024-02-29    4175.160144        2024   0.417516
362 2024-03-06  -18580.617032        2024  -1.858062
363 2024-03-13   30025.086036        2024   3.002509
364 2024-03-20  -75501.616459        2024  -7.550162

[365 rows x 4 columns]

In [3]:
df["Date"] = pd.to_datetime(df["Date"])
print(type(df["Date"]))
df['Trade Year'] = df['Date'].dt.year
df

<class 'pandas.core.series.Series'>

,Date,Position,Type,Expiry,Index,Contract,Entry Time,Exit Time,Entry Price,Exit Price,Quantity,PnL,Points,ROI,PnL_w_cs,ROI_w_cs,Trade Year
0,2017-01-05,CLOSED,HEDGE,2017-01-05,BANKNIFTY,17700PE,09:16:00,15:22:00,1.10,0.05,847.457627,-889.830508,-1.05,-0.088983,-888.855932,-0.088886,2017
1,2017-01-05,CLOSED,HEDGE,2017-01-05,BANKNIFTY,18300CE,09:16:00,15:22:00,2.30,0.05,819.672131,-1844.262295,-2.25,-0.184426,-1842.336065,-0.184234,2017
2,2017-01-05,CLOSED,STRADDLE,2017-01-05,BANKNIFTY,17800CE,09:16:00,13:56:00,200.00,302.65,-168.539326,-17300.561800,-102.65,-1.730056,-17385.278092,-1.738528,2017
3,2017-01-05,CLOSED,STRADDLE,2017-01-05,BANKNIFTY,17800PE,09:16:00,13:56:00,4.95,0.10,-168.539326,817.415730,4.85,0.081742,816.564607,0.081656,2017
4,2017-01-05,CLOSED,STRADDLE,2017-01-05,BANKNIFTY,17900CE,09:16:00,15:22:00,117.65,195.00,-167.597765,-12963.687150,-77.35,-1.296369,-13016.086591,-1.301609,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7203,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46300PE,13:59:00,15:22:00,21.30,0.30,-64.794816,1360.691145,21.00,0.136069,1359.291577,0.135929,2024
7204,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46200CE,14:12:00,15:22:00,149.90,119.65,-64.935065,1964.285714,30.25,0.196429,1946.782467,0.194678,2024
7205,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46200PE,14:12:00,15:22:00,28.80,0.15,-64.935065,1860.389610,28.65,0.186039,1858.509740,0.185851,2024
7206,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46100CE,14:24:00,15:22:00,162.95,218.80,-65.075922,-3634.490239,-55.85,-0.363449,-3659.332972,-0.365933,2024
7207,2024-03-20,CLOSED,REBALANCE,2024-03-20,BANKNIFTY,46100PE,14:24:00,15:22:00,25.05,0.10,-65.075922,1623.644252,24.95,0.162364,1622.007593,0.162201,2024

In [4]:
df = daily_pnl
stats_ = pd.DataFrame(index=range(2017, 2024), columns=['Total ROI', 'Total Trades', 'Win Rate', 'Avg Profit% per Trade', 'Avg Loss% per Trade', 'Max Drawdown', 'ROI/DD Ratio'])

# Iterate over each year
for year in range(2017, 2024):
    # Filter trades for the current year
    year_trades = df[(df['Trade Year'] == year)]
    
    # Calculate total ROI
    total_roi = year_trades['ROI_w_cs'].sum()
    
    # Calculate total number of trades
    total_trades = len(year_trades)
    
    # Calculate win rate
    win_rate = (year_trades['ROI_w_cs'] > 0).mean()*100
    
    # Calculate average profit per trade
    avg_profit = year_trades[year_trades['ROI'] > 0]['ROI_w_cs'].mean()
    
    # Calculate average loss per trade
    avg_loss = year_trades[year_trades['ROI_w_cs'] < 0]['ROI'].mean()
    
    # Calculate maximum drawdown
    max_drawdown = (year_trades['ROI_w_cs'].cumsum() - year_trades['ROI_w_cs'].cumsum().cummax()).min()
    
    # Calculate ROI/DD ratio
    roi_dd_ratio = total_roi / abs(max_drawdown)
    # 
    # Store the statistics in the DataFrame
    stats_.loc[year] = [total_roi, total_trades, win_rate, avg_profit, avg_loss, max_drawdown, roi_dd_ratio]

# Calculate overall statistics
overall_total_roi = stats_['Total ROI'].sum()
overall_total_trades = stats_['Total Trades'].sum()
overall_win_rate = (df['ROI_w_cs'] > 0).mean() * 100
overall_avg_profit = df[df['ROI_w_cs'] > 0]['ROI_w_cs'].mean()
overall_avg_loss = df[df['ROI_w_cs'] < 0]['ROI_w_cs'].mean()
overall_max_drawdown = (df['ROI_w_cs'].cumsum() - df['ROI_w_cs'].cumsum().cummax()).min()
overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)

# Store the overall statistics in the DataFrame
stats_.loc['Overall'] = [overall_total_roi, overall_total_trades, overall_win_rate, overall_avg_profit, overall_avg_loss, overall_max_drawdown, overall_roi_dd_ratio]
stats_

,Total ROI,Total Trades,Win Rate,Avg Profit% per Trade,Avg Loss% per Trade,Max Drawdown,ROI/DD Ratio
2017,15.582777,712,51.544944,0.577133,-0.51939,-15.179297,1.026581
2018,49.391334,816,59.926471,0.695848,-0.864825,-12.291762,4.018247
2019,82.874636,928,60.344828,0.807786,-0.992287,-13.450599,6.161408
2020,64.317958,1032,55.232558,1.296052,-1.429497,-33.812662,1.902186
2021,87.971658,1162,56.798623,0.944655,-1.053067,-18.192176,4.835686
2022,75.744151,1182,57.445008,0.850235,-0.994049,-11.667002,6.492169
2023,24.089387,1048,57.633588,0.609518,-0.768667,-16.121999,1.494194
Overall,399.971901,6880.0,57.172586,0.836574,-0.988039,-33.812662,11.829057

In [6]:
# WITH SLIPPAGES

import pandas as pd
df['Date'] = pd.to_datetime(df['Date'])
slippages = (df['Entry Price'] + df['Exit Price']) * 0.001 * df['Quantity']
df['PnL_w_cs'] = df['PnL'] - abs(slippages)
daily_pnl_2 = df.groupby(df['Date'].dt.date)['PnL_w_cs'].sum().reset_index()

# Rename the columns for clarity
daily_pnl_2.columns = ['Date', 'Total PnL']

daily_pnl_2["Date"] = pd.to_datetime(daily_pnl_2["Date"])
daily_pnl_2['Trade Year'] = daily_pnl_2['Date'].dt.year
daily_pnl_2["ROI"] = daily_pnl_2["Total PnL"]/10000
# If you want to ensure 'Date' column is in datetime format
daily_pnl_2['Date'] = pd.to_datetime(daily_pnl_2['Date'])

# Display the resulting DataFrame
print(daily_pnl_2)

          Date      Total PnL  Trade Year        ROI
0   2017-01-05   12003.057291        2017   1.200306
1   2017-01-12    4501.711544        2017   0.450171
2   2017-01-19   12984.456486        2017   1.298446
3   2017-01-25 -120586.058660        2017 -12.058606
4   2017-02-02   14113.608661        2017   1.411361
..         ...            ...         ...        ...
360 2024-02-21   12705.661897        2024   1.270566
361 2024-02-29    4134.165803        2024   0.413417
362 2024-03-06  -18600.016968        2024  -1.860002
363 2024-03-13   29996.464989        2024   2.999646
364 2024-03-20  -75537.057998        2024  -7.553706

[365 rows x 4 columns]

In [7]:
df = daily_pnl_2
stats_ = pd.DataFrame(index=range(2017, 2025), columns=['Total ROI', 'Total Trades', 'Win Rate', 'Avg Profit% per Trade', 'Avg Loss% per Trade', 'Max Drawdown', 'ROI/DD Ratio'])
df['ROI'] = df['ROI']
# Iterate over each year
for year in range(2017, 2025):
    # Filter trades for the current year
    year_trades = df[(df['Trade Year'] == year)]
    
    # Calculate total ROI
    total_roi = year_trades['ROI'].sum()
    
    # Calculate total number of trades
    total_trades = len(year_trades)
    
    # Calculate win rate
    win_rate = (year_trades['ROI'] > 0).mean()*100
    
    # Calculate average profit per trade
    avg_profit = year_trades[year_trades['ROI'] > 0]['ROI'].mean()
    
    # Calculate average loss per trade
    avg_loss = year_trades[year_trades['ROI'] < 0]['ROI'].mean()
    
    # Calculate maximum drawdown
    max_drawdown = (year_trades['ROI'].cumsum() - year_trades['ROI'].cumsum().cummax()).min()
    
    # Calculate ROI/DD ratio
    roi_dd_ratio = total_roi / abs(max_drawdown)
    
    # Store the statistics in the DataFrame
    stats_.loc[year] = [total_roi, total_trades, win_rate, avg_profit, avg_loss, max_drawdown, roi_dd_ratio]

# Calculate overall statistics
overall_total_roi = stats_['Total ROI'].sum()
overall_total_trades = stats_['Total Trades'].sum()
overall_win_rate = (df['ROI'] > 0).mean() * 100
overall_avg_profit = df[df['ROI'] > 0]['ROI'].mean()
overall_avg_loss = df[df['ROI'] < 0]['ROI'].mean()
overall_max_drawdown = (df['ROI'].cumsum() - df['ROI'].cumsum().cummax()).min()
overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)

# Store the overall statistics in the DataFrame
stats_.loc['Overall'] = [overall_total_roi, overall_total_trades, overall_win_rate, overall_avg_profit, overall_avg_loss, overall_max_drawdown, overall_roi_dd_ratio]
stats_

,Total ROI,Total Trades,Win Rate,Avg Profit% per Trade,Avg Loss% per Trade,Max Drawdown,ROI/DD Ratio
2017,-37.243646,50,56.0,1.37915,-3.448175,-45.874891,-0.811853
2018,26.309648,50,64.0,2.113488,-2.295665,-7.982375,3.295967
2019,76.382581,51,72.54902,2.807924,-1.965044,-7.467565,10.228579
2020,47.72625,52,63.461538,3.522962,-3.606921,-32.655227,1.461519
2021,80.555058,50,74.0,3.332966,-3.289591,-10.890286,7.396964
2022,75.350955,51,70.588235,2.754779,-1.588073,-4.020935,18.739662
2023,21.259697,50,62.0,1.98084,-2.112965,-12.506652,1.699871
2024,-2.571592,11,72.727273,1.982714,-6.144436,-13.749678,-0.187029
Overall,287.768951,365.0,66.30137,2.587431,-2.751133,-45.874891,6.272908