In [30]:
import pandas as pd
import datetime as dt

In [31]:
mtrend = pd.read_csv('MTrend tb.csv')
molotov = pd.read_csv('molotov.csv')
wave = pd.read_csv('wave.csv')
mtrend['ROI%'] = mtrend['ROI% PF']
wave['ROI%'] = wave['ROI% PF']
molotov['Entry Date'] = pd.to_datetime(molotov['date'] + ' ' + molotov['Entry Time'])
mtrend['Entry Date'] = mtrend['Entry Time']
wave['Entry Date'] = wave['Entry Time']

In [32]:
# mtrend.head()

In [33]:
# molotov.head()

In [34]:
# Define the start and end dates for the range
start_date = dt.date(2019, 1, 1)
end_date = dt.date(2024, 6, 30)
mtrend['Entry Time'] = pd.to_datetime(mtrend['Entry Time'])
wave['Entry Time'] = pd.to_datetime(wave['Entry Time'])
# Filter the DataFrame within the specified date range
mtrend = mtrend[(mtrend['Entry Time'].dt.date >= start_date) & (mtrend['Entry Time'].dt.date <= end_date)]
wave = wave[(wave['Entry Time'].dt.date >= start_date) & (wave['Entry Time'].dt.date <= end_date)]

In [35]:
combined_df = pd.concat([mtrend, wave, molotov], ignore_index=True)

In [36]:
combined_df

,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,...,type,initial sl,TSL,Exit date,Remark,Slippage,Highest High,Lowest Low,Max ROI%,Margin
0,2019-01-01 13:15:00,LONG,2019-01-01 14:15:00,10830.35,10807.10,10808.370000,2019-01-02 12:15:00,10807.10,-23.25,-27.577490,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-01 14:15:00,LONG,2019-01-01 15:15:00,27395.35,27076.60,27201.263889,2019-01-02 13:15:00,27133.20,-262.15,-267.602855,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-03 09:15:00,LONG,2019-01-03 10:15:00,10810.85,10750.00,10750.000000,2019-01-03 11:15:00,10750.00,-60.85,-65.162170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-03 12:15:00,LONG,2019-01-03 13:15:00,27087.80,26977.75,26977.750000,2019-01-03 13:15:00,26977.75,-110.05,-115.456555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-04 10:15:00,LONG,2019-01-04 11:15:00,27132.15,26926.90,27554.119444,2019-01-10 14:15:00,27521.20,389.05,383.584665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3428,NaN,NaN,12:35:00,357.50,NaN,NaN,14:00:00,451.95,-94.45,NaN,...,C,451.95,0.0000,2024-05-31,SL hit,8.0945,454.20,351.25,0.132345,59.820011
3429,NaN,NaN,13:35:00,367.05,NaN,NaN,09:30:00,500.00,-132.95,NaN,...,P,500.00,154.7025,2024-06-04,SL hit,8.6705,561.50,50.00,4.769462,42.403159
3430,NaN,NaN,15:05:00,797.30,NaN,NaN,15:25:00,0.05,797.25,NaN,...,P,1395.50,1.0550,2024-06-06,EOD exit,7.9735,903.30,0.05,2.665496,9.382314
3431,NaN,NaN,09:50:00,210.95,NaN,NaN,15:25:00,0.05,210.90,NaN,...,C,265.90,0.0000,2024-06-06,EOD exit,2.1100,245.25,0.05,7.676069,105.550500
3432,NaN,NaN,12:30:00,97.75,NaN,NaN,15:25:00,0.05,97.70,NaN,...,P,219.70,0.1675,2024-06-13,EOD exit,0.9780,105.65,0.05,1.602296,46.740467

In [37]:
# mtrend.head()

In [38]:
# molotov.head()

In [39]:
combined_df['ROI%'] /= 3

In [40]:
combined_df['Entry Date'] = pd.to_datetime(combined_df['Entry Date'])
combined_df = combined_df.sort_values(by='Entry Date')

In [41]:
def generate_stats(tb_expiry, variation):
    stats_df8 = pd.DataFrame(
        index=range(2019, 2025),
        columns=[
            "Total ROI",
            "Total Trades",
            "Win Rate",
            "Avg Profit% per Trade",
            "Avg Loss% per Trade",
            "Max Drawdown",
            "ROI/DD Ratio",
            "Variation",
        ],
    )
    combined_df_sorted = tb_expiry
    # combined_df_sorted = tb_expiry_ce
    # combined_df_sorted = tb_expiry_pe
    
    # Iterate over each year
    for year in range(2019, 2025):
        # Filter trades for the current year
        year_trades = combined_df_sorted[(combined_df_sorted["Trade Year"] == year)]
    
        # Calculate total ROI
        total_roi = year_trades["ROI%"].sum()
    
        # Calculate total number of trades
        total_trades = len(year_trades)
    
        # Calculate win rate
        win_rate = (year_trades["ROI%"] > 0).mean() * 100
    
        # Calculate average profit per trade
        avg_profit = year_trades[year_trades["ROI%"] > 0]["ROI%"].mean()
    
        # Calculate average loss per trade
        avg_loss = year_trades[year_trades["ROI%"] < 0]["ROI%"].mean()
    
        # Calculate maximum drawdown
        max_drawdown = (
            year_trades["ROI%"].cumsum() - year_trades["ROI%"].cumsum().cummax()
        ).min()
    
        # Calculate ROI/DD ratio
        roi_dd_ratio = total_roi / abs(max_drawdown)

        variation = variation
    
        # Store the statistics in the DataFrame
        stats_df8.loc[year] = [
            total_roi,
            total_trades,
            win_rate,
            avg_profit,
            avg_loss,
            max_drawdown,
            roi_dd_ratio,
            variation,
        ]
    
    # Calculate overall statistics
    overall_total_roi = stats_df8["Total ROI"].sum()
    overall_total_trades = stats_df8["Total Trades"].sum()
    overall_win_rate = (combined_df_sorted["ROI%"] > 0).mean() * 100
    overall_avg_profit = combined_df_sorted[combined_df_sorted["ROI%"] > 0]["ROI%"].mean()
    overall_avg_loss = combined_df_sorted[combined_df_sorted["ROI%"] < 0]["ROI%"].mean()
    overall_max_drawdown = (
        combined_df_sorted["ROI%"].cumsum() - combined_df_sorted["ROI%"].cumsum().cummax()
    ).min()
    overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)
    overall_variation = variation
    
    # Store the overall statistics in the DataFrame
    stats_df8.loc["Overall"] = [
        overall_total_roi,
        overall_total_trades,
        overall_win_rate,
        overall_avg_profit,
        overall_avg_loss,
        overall_max_drawdown,
        overall_roi_dd_ratio,
        overall_variation,
    ]
    return {overall_roi_dd_ratio : stats_df8}

In [44]:
stats = generate_stats(combined_df, 'MTrend + Wave + Molotov')

In [45]:
for x, y in stats.items():
    z = pd.DataFrame(y)

z

,Total ROI,Total Trades,Win Rate,Avg Profit% per Trade,Avg Loss% per Trade,Max Drawdown,ROI/DD Ratio,Variation
2019,83.858747,586,35.324232,0.991479,-0.320257,-9.538272,8.791817,MTrend + Wave + Molotov
2020,201.867438,559,39.713775,1.642237,-0.482816,-11.340679,17.800296,MTrend + Wave + Molotov
2021,115.135216,584,38.184932,1.128176,-0.377972,-12.760968,9.022452,MTrend + Wave + Molotov
2022,85.184261,672,35.267857,1.028794,-0.36469,-17.359735,4.907002,MTrend + Wave + Molotov
2023,96.569395,681,37.73862,0.815951,-0.266816,-8.479654,11.388365,MTrend + Wave + Molotov
2024,34.240233,351,35.327635,0.857913,-0.317802,-7.798554,4.390587,MTrend + Wave + Molotov
Overall,616.855291,3433,36.993883,1.087638,-0.353419,-17.359735,35.533682,MTrend + Wave + Molotov

In [29]:
combined_df.to_csv('Combined_Wave_Molotov.csv')