In [29]:
import pandas as pd
import datetime as dt
tradebook_df = pd.read_csv('WAVE_1x_nifty.csv')
df = pd.read_csv("../data/nifty_wave.csv")
df["datetime"] = pd.to_datetime(df["time"])
df = df[df["datetime"].dt.year >= 2018]

INDEX = 'NIFTY'
PORTFOLIO_VALUE = 10_00_000
# RPT_PCT = 0.01 # 1% RPT
SLIPPAGE_ = 0.0001
# LEVERAGE_ = 5

In [30]:
tradebook_df.rename(columns={'Unnamed: 0': 'Trade No.'}, inplace=True)
tradebook_df.head()

,Trade No.,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,PnL,Remarks,Qty,Leverage,ROI%,Trade Year,Trade Month
0,0,2017-01-02 12:15:00,LONG,2017-01-02 13:15:00,26540.57,26381.32658,26381.326580,2017-01-09 15:15:00,26711.96,171.39,166.064747,6642.58988,MACD Reversal,40,1,0.664259,2017,1
1,1,2017-01-10 10:15:00,LONG,2017-01-10 11:15:00,26863.63,26702.44822,27177.240833,2017-01-20 10:15:00,27199.24,335.61,330.203713,13208.14852,MACD Reversal,40,1,1.320815,2017,1
2,2,2017-01-24 11:15:00,LONG,2017-01-24 12:15:00,27268.50,27104.88900,27476.671333,2017-02-01 09:15:00,27655.32,386.82,381.327618,15253.10472,MACD Reversal,40,1,1.525310,2017,1
3,3,2017-02-01 12:15:00,LONG,2017-02-01 13:15:00,28003.13,27835.11122,28123.293000,2017-02-09 11:15:00,28221.60,218.47,212.847527,8513.90108,MACD Reversal,40,1,0.851390,2017,2
4,4,2017-02-09 14:15:00,LONG,2017-02-09 15:15:00,28334.77,28164.76138,28258.359333,2017-02-13 12:15:00,28236.79,-97.98,-103.637156,-4145.48624,TSL Hit,40,1,-0.414549,2017,2

In [31]:
import pandas as pd

def calculate_day_by_day_pnl(df, tradebook_df):
    pnl_records = []
    
    for _, trade in tradebook_df.iterrows():
        trade_no = trade['Trade No.']
        start_date = pd.to_datetime(trade['Entry Time']).date()
        end_date = pd.to_datetime(trade['Exit Time']).date()
        # direction = trade['Trade_Type']  # 'long' or 'short'
        entry_price = trade['Entry Price']
        qty = trade['Qty']
        total_slippage = trade['Points Captured'] - trade['After Costs']
        
        # Filter the spot data for the trade duration
        trade_data = df[(df['datetime'].dt.date >= start_date) & (df['datetime'].dt.date <= end_date)].copy()
        
        # Aggregate data into daily OHLC
        trade_data['date'] = trade_data['datetime'].dt.date
        daily_ohlc = trade_data.groupby('date').agg(
            open_price=('open', 'first'),
            high_price=('high', 'max'),
            low_price=('low', 'min'),
            close_price=('close', 'last')
        ).reset_index()

        num_days = len(daily_ohlc)
        slippage_per_day = total_slippage / num_days if num_days > 0 else 0
        
        # Calculate day-by-day PnL
        for i, row in daily_ohlc.iterrows():
            date = row['date']
            exit_price = row['close_price']
            if i == 0:
                day_entry_price = entry_price
            else:
                day_entry_price = daily_ohlc.iloc[i - 1]['close_price']
            
            # if direction == 'Long':
            pnl = exit_price - day_entry_price
            # elif direction == 'short':
            #     pnl = day_entry_price - exit_price
            
            pnl_records.append({
                'Trade No.': trade_no,
                'Portfolio': PORTFOLIO_VALUE,
                'Date': date,
                'Entry Price': day_entry_price,
                'Exit Price': exit_price,
                'Points': pnl,
                'Qty': qty,
                'Slippage': slippage_per_day,
                'PnL': ((pnl - slippage_per_day) * qty),
                'ROI%': ((pnl - slippage_per_day) * qty) * 100 / PORTFOLIO_VALUE,
                'Index': INDEX,
            })
    
    # Convert the records into a DataFrame
    pnl_df = pd.DataFrame(pnl_records)
    return pnl_df

In [32]:
tb2 = calculate_day_by_day_pnl(df, tradebook_df)

In [33]:
tb2

,Trade No.,Portfolio,Date,Entry Price,Exit Price,Points,Qty,Slippage,PnL,ROI%,Index
0,45,1000000,2018-01-01,33993.86,33827.90,-165.96,30,6.778376,-5182.151271,-0.518215,SENSEX
1,46,1000000,2018-01-04,33979.61,33980.91,1.30,30,0.389023,27.329317,0.002733,SENSEX
2,46,1000000,2018-01-05,33980.91,34172.14,191.23,30,0.389023,5725.229317,0.572523,SENSEX
3,46,1000000,2018-01-08,34172.14,34331.51,159.37,30,0.389023,4769.429317,0.476943,SENSEX
4,46,1000000,2018-01-09,34331.51,34431.05,99.54,30,0.389023,2974.529317,0.297453,SENSEX
...,...,...,...,...,...,...,...,...,...,...,...
1234,334,1000000,2024-11-26,80171.54,80005.93,-165.61,10,3.150969,-1687.609690,-0.168761,SENSEX
1235,334,1000000,2024-11-27,80005.93,80244.75,238.82,10,3.150969,2356.690310,0.235669,SENSEX
1236,334,1000000,2024-11-28,80244.75,79165.22,-1079.53,10,3.150969,-10826.809690,-1.082681,SENSEX
1237,335,1000000,2024-11-29,79788.75,79747.12,-41.63,10,7.954938,-495.849384,-0.049585,SENSEX
1238,335,1000000,2024-12-02,79747.12,80253.78,506.66,10,7.954938,4987.050616,0.498705,SENSEX

In [34]:
# tb2.to_csv('JJPP_bnf_day-wise.csv', index=False)

In [35]:
tb2['Points'].sum()

52512.57999999999

In [39]:
(tradebook_df['Points Captured']).sum()

54939.62825999998

In [37]:
tb2['ROI%'].sum()

107.99804218740599

In [40]:
tb2.to_csv('sensex-daily-wave.csv', index=False)