In [84]:
import pandas as pd

mtrend = pd.read_csv('MTrend tb.csv')
wave = pd.read_csv('Wave Tb.csv')

In [85]:
mtrend['Strategy'] = 'MTREND'
wave['Strategy'] = 'WAVE'

In [86]:
# mtrend['ROI% PF'] *= 2

In [87]:
combined_df = pd.concat([mtrend, wave], ignore_index=True)

In [88]:
combined_df = combined_df.sort_values(by='Signal Generated At')

In [89]:
combined_df['ROI% PF'] /= 10

In [90]:
combined_df.tail()

,Signal Generated At,Trade Type,Entry Time,Entry Price,Initial SL,Final SL,Exit Time,Exit Price,Points Captured,After Costs,...,ROI%,Trade Year,Trade Month,Index,Allocation,Portfolio,ROI% PF,Strategy,Qty apAlloc,PnL apAlloc
3497,2024-11-28 11:15:00,LONG,2024-11-28 11:45:00,52183.60,51400.84600,51400.846000,2024-11-28 12:15:00,52085.9000,-97.7000,-108.126950,...,-0.973143,2024,11,BANKNIFTY,250000.0,1000000.0,-0.024329,WAVE,22.5,-2432.856375
1703,2024-11-29 12:15:00,LONG,2024-11-29 13:15:00,51926.50,51811.60000,51811.600000,2024-12-02 09:15:00,51811.6000,-114.9000,-125.273810,...,-1.227683,2024,11,BANKNIFTY,7500000.0,30000000.0,-0.030692,MTREND,NaN,NaN
1702,2024-11-29 12:15:00,LONG,2024-11-29 13:15:00,24131.95,24089.40000,24133.526250,2024-12-02 09:15:00,24089.4000,-42.5500,-52.194270,...,-1.374449,2024,11,NIFTY,7500000.0,30000000.0,-0.034361,MTREND,NaN,NaN
3498,2024-11-29 12:15:00,LONG,2024-11-29 13:15:00,79788.75,79310.01750,79310.017500,2024-12-02 09:15:00,79310.0175,-478.7325,-494.642377,...,-4.946424,2024,11,SENSEX,250000.0,1000000.0,-0.123661,WAVE,25.0,-12366.059419
3499,2024-12-03 09:15:00,LONG,2024-12-03 09:45:00,52487.25,51699.94125,53142.216667,2024-12-05 09:45:00,53032.6000,545.3500,534.798015,...,4.813182,2024,12,BANKNIFTY,250000.0,1000000.0,0.120330,WAVE,22.5,12032.955337

In [91]:
def generate_stats(tb_expiry):
    stats_df8 = pd.DataFrame(
        index=range(2017, 2025),
        columns=[
            "Total ROI",
            "Total Trades",
            "Win Rate",
            "Avg Profit% per Trade",
            "Avg Loss% per Trade",
            
            "Max Drawdown",
            "ROI/DD Ratio",
            
        ],
    )
    combined_df_sorted = tb_expiry
    # combined_df_sorted = tb_expiry_ce
    # combined_df_sorted = tb_expiry_pe
    
    # Iterate over each year
    for year in range(2017, 2025):
        # Filter trades for the current year
        year_trades = combined_df_sorted[(combined_df_sorted["Trade Year"] == year)]
    
        # Calculate total ROI
        total_roi = year_trades["ROI% PF"].sum()
    
        # Calculate total number of trades
        total_trades = len(year_trades)
    
        # Calculate win rate
        win_rate = (year_trades["ROI% PF"] >= 0).mean() * 100
    
        # Calculate average profit per trade
        avg_profit = year_trades[year_trades["ROI% PF"] > 0]["ROI% PF"].mean()
    
        # Calculate average loss per trade
        avg_loss = year_trades[year_trades["ROI% PF"] < 0]["ROI% PF"].mean()
    
        # Calculate maximum drawdown
        max_drawdown = (
            year_trades["ROI% PF"].cumsum() - year_trades["ROI% PF"].cumsum().cummax()
        ).min()
    
        # Calculate ROI/DD ratio
        roi_dd_ratio = total_roi / abs(max_drawdown)

        # variation = f'{signal_ma} , {trailing_ma}, {time_of_day}'
    
        # Store the statistics in the DataFrame
        stats_df8.loc[year] = [
            total_roi,
            total_trades,
            win_rate,
            avg_profit,
            avg_loss,
            max_drawdown,
            roi_dd_ratio,
            # variation,
        ]
    
    # Calculate overall statistics
    overall_total_roi = stats_df8["Total ROI"].sum()
    overall_total_trades = stats_df8["Total Trades"].sum()
    overall_win_rate = (combined_df_sorted["ROI% PF"] >= 0).mean() * 100
    overall_avg_profit = combined_df_sorted[combined_df_sorted["ROI% PF"] > 0]["ROI% PF"].mean()
    overall_avg_loss = combined_df_sorted[combined_df_sorted["ROI% PF"] < 0]["ROI% PF"].mean()
    overall_max_drawdown = (
        combined_df_sorted["ROI% PF"].cumsum() - combined_df_sorted["ROI% PF"].cumsum().cummax()
    ).min()
    overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)
    # overall_variation = variation
    
    # Store the overall statistics in the DataFrame
    stats_df8.loc["Overall"] = [
        overall_total_roi,
        overall_total_trades,
        overall_win_rate,
        overall_avg_profit,
        overall_avg_loss,
        overall_max_drawdown,
        overall_roi_dd_ratio,
        # overall_variation,
    ]
    return pd.DataFrame(stats_df8)

In [92]:
stats = generate_stats(combined_df)
stats

,Total ROI,Total Trades,Win Rate,Avg Profit% per Trade,Avg Loss% per Trade,Max Drawdown,ROI/DD Ratio
2017,9.933447,367,29.700272,0.262367,-0.072343,-2.837396,3.500902
2018,15.076528,386,34.715026,0.251491,-0.073902,-3.964242,3.80313
2019,13.863617,427,31.147541,0.263308,-0.071961,-4.459588,3.108721
2020,51.217914,387,36.434109,0.567795,-0.11724,-3.322568,15.415157
2021,23.953839,417,34.052758,0.335253,-0.086007,-5.177572,4.626462
2022,18.835467,507,31.163708,0.295581,-0.079846,-5.338752,3.528065
2023,22.442697,523,34.799235,0.219027,-0.051086,-3.227004,6.954653
2024,9.220079,486,33.539095,0.190835,-0.067758,-4.17177,2.210112
Overall,164.543588,3500.0,33.2,0.294883,-0.07618,-5.338752,30.820609

# MTrend + WAVE -> Combined (Equal Allocation)

In [93]:
combined_df.to_csv('MTrend_WAVE_combined.csv')