In [718]:
import pandas as pd
import polars as pl
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import mplfinance as mpf
from plotly.subplots import make_subplots
from dash import Dash, dcc, html
import pandas_market_calendars as mcal
import sys
import asyncio
nse = mcal.get_calendar('NSE')

In [719]:
import sys
sys.path.append('..')
from tooling.filter import find_atm, option_tool
from tooling.fetch import fetch_option_data, fetch_spot_data
from tooling.filter import find_atm
from tooling.enums import Index, AssetClass, StrikeSpread, Spot

In [720]:
pd.set_option("display.max_rows", 25_000)
pd.set_option("display.max_columns", 500)
pl.Config.set_tbl_cols(500)
pl.Config.set_tbl_rows(25_000)

polars.config.Config

In [844]:
stock = pd.read_csv('../data/Nifty Next50 FNO Data/jindalstel_10_1_monthly.csv')
current_stock = 'JINDALSTEL'
stock

           time    open    high     low   close    Up Trend  Down Trend
0    2010-03-02  727.35  727.35  712.50  712.50         NaN         NaN
1    2010-04-01  719.05  754.00  711.50  749.10         NaN         NaN
2    2010-05-03  738.60  744.15  573.10  654.75         NaN         NaN
3    2010-06-01  651.20  691.00  606.90  628.45         NaN         NaN
4    2010-07-01  625.00  653.90  614.40  627.05         NaN         NaN
5    2010-08-02  630.10  718.40  617.30  688.45         NaN         NaN
6    2010-09-01  692.80  724.80  686.00  712.00         NaN         NaN
7    2010-10-01  713.05  760.50  686.10  699.50         NaN         NaN
8    2010-11-01  704.00  725.20  577.10  641.40         NaN         NaN
9    2010-12-01  642.75  732.10  642.50  717.70         NaN  768.305000
10   2011-01-03  718.90  738.95  647.50  666.55         NaN  768.305000
11   2011-02-01  663.65  697.95  605.20  662.20         NaN  734.694550
12   2011-03-01  665.10  706.30  635.50  700.00         NaN  734.694550
13   2011-04-01  703.00  727.65  651.15  656.85         NaN  734.694550
14   2011-05-02  664.25  664.25  616.00  654.20         NaN  718.163952
15   2011-06-01  656.85  662.30  603.00  654.50         NaN  708.815057
16   2011-07-01  655.05  664.00  584.00  588.30         NaN  700.548551
17   2011-08-01  589.10  590.75  451.50  519.75         NaN  603.943696
18   2011-09-02  523.70  571.00  498.80  504.30         NaN  603.943696
19   2011-10-03  496.05  605.30  443.75  566.50         NaN  603.943696
20   2011-11-01  561.15  588.00  478.00  503.50         NaN  603.943696
21   2011-12-01  520.15  545.80  440.15  455.70         NaN  586.126276
22   2012-01-02  456.30  555.00  444.75  545.75         NaN  586.126276
23   2012-02-01  548.00  664.10  548.00  590.55  508.839966         NaN
24   2012-03-01  589.75  630.70  518.20  549.45  508.839966         NaN
25   2012-04-02  547.75  557.95  471.80  507.75         NaN  612.355127
26   2012-05-02  508.70  518.30  442.00  444.80         NaN  575.512115
27   2012-06-01  442.10  477.00  412.45  473.00         NaN  537.005903
28   2012-07-02  474.95  483.40  391.70  401.60         NaN  529.772813
29   2012-08-01  400.55  427.15  343.00  352.85         NaN  476.490532
30   2012-09-03  353.20  453.90  322.00  430.25         NaN  476.490532
31   2012-10-01  432.55  442.95  374.45  390.55         NaN  476.490532
32   2012-11-01  389.30  407.00  365.05  404.35         NaN  473.710823
33   2012-12-03  405.65  475.40  401.65  451.95         NaN  473.710823
34   2013-01-01  457.90  478.00  391.65  423.40         NaN  473.710823
35   2013-02-01  424.00  427.85  341.00  351.05         NaN  470.778215
36   2013-03-01  355.30  371.90  335.00  350.30         NaN  434.857893
37   2013-04-01  353.40  362.00  297.00  306.20         NaN  409.267104
38   2013-05-02  306.00  339.25  284.20  286.00         NaN  389.020393
39   2013-06-03  287.10  296.90  195.85  218.85         NaN  326.045854
40   2013-07-01  215.15  228.95  189.00  201.55         NaN  284.673769
41   2013-08-01  201.10  248.10  182.70  221.80         NaN  284.673769
42   2013-09-02  221.95  266.55  217.20  238.50         NaN  284.673769
43   2013-10-01  237.05  259.95  231.00  240.95         NaN  284.673769
44   2013-11-01  242.30  261.70  234.15  260.75         NaN  284.673769
45   2013-12-02  261.25  291.35  248.25  263.65         NaN  284.673769
46   2014-01-01  264.35  271.80  249.45  251.75         NaN  284.673769
47   2014-02-03  250.00  254.80  231.25  240.15         NaN  284.673769
48   2014-03-03  240.10  301.20  238.15  294.20  214.444575         NaN
49   2014-04-01  296.85  305.50  250.00  256.95  222.492618         NaN
50   2014-05-02  260.00  321.00  237.55  300.10  222.492618         NaN
51   2014-06-02  301.10  351.20  300.00  325.70  268.211020         NaN
52   2014-07-01  326.90  338.70  274.10  276.65  268.211020         NaN
53   2014-08-01  273.60  301.10  231.90  234.65         NaN  325.719074
54   2014-09-01  237.05  254.40  168.60  174.20         NaN  273.377166
55   2014-10-01  176.50  176.50  128.10  162.30         NaN  212.829450
56   2014-11-03  163.50  175.00  139.60  141.60         NaN  212.829450
57   2014-12-01  141.85  158.30  125.55  153.05         NaN  197.414854
58   2015-01-01  153.65  167.80  145.65  160.05         NaN  197.414854
59   2015-02-02  158.85  208.75  138.50  197.50  119.659718         NaN
60   2015-03-02  193.40  202.75  142.00  157.85  119.659718         NaN
61   2015-04-01  156.80  170.45  136.20  140.75  119.659718         NaN
62   2015-05-04  141.00  149.20  110.20  120.05  119.659718         NaN
63   2015-06-01  118.55  122.60   84.75   85.90         NaN  153.579546
64   2015-07-01   86.20   93.60   72.00   79.25         NaN  129.874092
65   2015-08-03   79.25   87.75   60.75   68.10         NaN  119.316683
66   2015-09-01   68.50   69.85   56.10   61.05         NaN  104.910014
67   2015-10-01   61.65   85.85   60.15   80.40         NaN  104.910014
68   2015-11-02   79.85   94.60   70.00   91.55         NaN  104.910014
69   2015-12-01   91.90   98.70   84.00   96.65         NaN  104.910014
70   2016-01-01   96.60   97.90   56.90   64.55         NaN  104.910014
71   2016-02-01   64.90   66.05   48.10   53.60         NaN   91.992424
72   2016-03-01   54.20   68.25   53.75   60.45         NaN   91.992424
73   2016-04-01   59.75   79.20   59.70   70.25         NaN   91.992424
74   2016-05-02   68.60   72.35   57.70   63.70         NaN   91.992424
75   2016-06-01   63.80   68.90   60.65   68.35         NaN   91.992424
76   2016-07-01   69.25   90.05   66.45   84.15         NaN   91.992424
77   2016-08-01   85.05   92.00   77.10   85.90         NaN   91.992424
78   2016-09-01   86.00   88.10   74.00   76.50         NaN   91.992424
79   2016-10-03   77.50   86.60   74.65   75.80         NaN   91.992424
80   2016-11-01   75.35   79.40   63.35   71.05         NaN   91.992424
81   2016-12-01   71.15   77.35   64.95   69.45         NaN   91.992424
82   2017-01-02   69.65   84.65   69.05   80.20         NaN   91.992424
83   2017-02-01   80.65  129.75   78.85  125.85   80.170223         NaN
84   2017-03-01  125.80  131.85  113.00  121.70   98.823201         NaN
85   2017-04-03  122.20  135.70  109.30  114.85   98.823201         NaN
86   2017-05-02  115.35  129.85  102.60  122.50   98.823201         NaN
87   2017-06-01  122.40  129.25  115.45  123.90   99.173388         NaN
88   2017-07-03  123.90  159.20  123.50  154.45  116.921050         NaN
89   2017-08-01  154.55  160.00  114.50  137.90  116.921050         NaN
90   2017-09-01  139.00  154.90  131.70  135.30  117.097550         NaN
91   2017-10-03  137.00  171.00  136.40  163.60  126.547795         NaN
92   2017-11-01  164.50  178.95  156.70  173.20  141.163016         NaN
93   2017-12-01  173.95  208.30  158.10  206.25  154.184214         NaN
94   2018-01-01  206.00  294.70  200.75  267.90  212.215793         NaN
95   2018-02-01  267.10  279.50  234.30  255.65  220.421713         NaN
96   2018-03-01  253.30  259.20  205.50  220.15         NaN  270.550458
97   2018-04-02  223.80  264.40  218.10  253.60         NaN  270.550458
98   2018-05-02  253.75  265.95  222.70  230.45         NaN  270.550458
99   2018-06-01  229.40  251.00  209.80  223.90         NaN  270.010934
100  2018-07-02  223.50  230.20  177.65  205.90         NaN  244.829840
101  2018-08-01  209.85  229.20  189.25  222.25         NaN  244.829840
102  2018-09-03  223.05  246.60  186.50  196.20         NaN  244.829840
103  2018-10-01  191.05  199.20  157.15  172.20         NaN  220.844579
104  2018-11-01  172.00  193.30  150.50  154.35         NaN  214.582621
105  2018-12-03  159.00  173.00  140.80  165.70         NaN  198.534359
106  2019-01-01  165.95  166.30  127.20  135.75         NaN  188.130923
107  2019-02-01  135.50  164.55  123.50  157.85         NaN  185.372831
108  2019-03-01  159.00  183.25  158.00  181.15         NaN  185.372831
109  2019-04-01  184.45  192.10  166.95  178.75         NaN  185.372831
110  2019-05-02  177.90  184.20  143.25  159.90         NaN  185.372831
111  2019-06-03  159.50  171.40  137.00  143.10         NaN  185.372831
112  2019-07-01  145.85  148.85  128.65  135.75         NaN  175.098359
113  2019-08-01  134.40  134.40   91.20   97.20         NaN  149.968524
114  2019-09-03   96.70  114.50   91.25  103.90         NaN  138.651671
115  2019-10-01  104.80  119.95   91.45  116.65         NaN  138.651671
116  2019-11-01  116.65  166.75  116.45  161.70  105.025896         NaN
117  2019-12-02  162.65  169.40  132.50  168.55  114.343307         NaN
118  2020-01-01  168.80  189.45  164.75  176.45  141.683976         NaN
119  2020-02-01  175.25  203.20  151.35  153.40  141.683976         NaN
120  2020-03-02  159.55  164.40   80.00   82.85         NaN  163.993479
121  2020-04-01   82.60   97.80   62.15   95.35         NaN  121.154131
122  2020-05-04   89.60  121.75   83.40  120.60         NaN  121.154131
123  2020-06-01  122.45  165.00  122.45  161.65  102.478404         NaN
124  2020-07-01  163.15  187.00  152.10  185.50  128.938063         NaN
125  2020-08-03  185.35  238.90  183.75  205.65  169.259257         NaN
126  2020-09-01  206.85  227.00  159.60  187.00  169.259257         NaN
127  2020-10-01  188.75  214.40  180.65  191.60  169.259257         NaN
128  2020-11-02  192.60  253.40  187.30  245.25  174.577173         NaN
129  2020-12-01  248.05  287.80  244.20  267.60  220.444456         NaN
130  2021-01-01  269.00  311.45  259.00  262.15  238.980010         NaN
131  2021-02-01  263.45  349.50  258.00  337.30  252.979509         NaN
132  2021-03-01  339.95  357.00  297.80  346.05  275.786558         NaN
133  2021-04-01  348.00  462.20  348.00  443.35  347.032903         NaN
134  2021-05-03  439.65  504.00  383.10  409.45  379.199612         NaN
135  2021-06-01  411.40  429.80  364.60  398.55  379.199612         NaN
136  2021-07-01  401.10  448.35  378.30  433.45  379.199612         NaN
137  2021-08-02  434.10  436.55  357.10  378.35         NaN  461.635349
138  2021-09-01  379.90  409.65  347.15  390.20         NaN  444.447919
139  2021-10-01  386.00  473.20  379.85  417.70         NaN  444.447919
140  2021-11-01  422.50  439.50  341.00  344.75         NaN  444.447919
141  2021-12-01  352.15  409.00  344.15  378.75         NaN  444.447919
142  2022-01-03  379.30  424.15  361.50  386.35         NaN  444.447919
143  2022-02-01  389.95  446.00  368.30  425.70         NaN  444.447919
144  2022-03-02  423.45  544.50  421.55  534.60  406.859404         NaN
145  2022-04-01  535.00  579.15  514.00  540.85  471.510963         NaN
146  2022-05-02  532.30  541.45  371.55  379.15         NaN  541.047633
147  2022-06-01  381.90  387.10  303.90  327.55         NaN  429.912870
148  2022-07-01  325.90  396.60  320.20  391.35         NaN  429.912870
149  2022-08-01  392.85  434.50  372.40  433.10  321.989575         NaN
150  2022-09-01  426.40  468.00  385.75  430.90  345.335618         NaN
151  2022-10-03  427.95  474.00  418.30  461.15  367.194556         NaN
152  2022-11-01  454.15  543.85  454.15  538.95  418.970100         NaN
153  2022-12-01  542.55  599.50  523.55  584.65  481.903090         NaN
154  2023-01-02  587.20  615.50  568.20  588.70  515.460281         NaN
155  2023-02-01  583.75  627.10  547.50  552.90  515.460281         NaN
156  2023-03-01  555.95  595.30  530.60  549.85  515.460281         NaN
157  2023-04-03  550.00  591.40  540.25  584.70  515.460281         NaN
158  2023-05-02  588.50  607.75  507.00  521.35  515.460281         NaN
159  2023-06-01  522.80  606.65  511.05  585.20  515.460281         NaN
160  2023-07-03  584.85  679.75  583.80  674.15  552.144519         NaN
161  2023-08-01  675.55  702.00  631.90  688.25  588.272567         NaN
162  2023-09-01  689.40  724.75  679.85  705.90  627.000311         NaN
163  2023-10-03  703.95  706.85  631.00  636.40  627.000311         NaN
164  2023-11-01  620.00  679.35  585.60  676.30  627.000311         NaN
165  2023-12-01  682.00  772.15  675.05  753.55  644.415176         NaN
166  2024-01-01  754.00  769.25  686.70  762.70  648.453659         NaN
167  2024-02-01  769.00  807.50  709.00  780.20  676.830793         NaN
168  2024-03-01  781.85  868.65  760.50  853.20  730.482714         NaN
169  2024-04-01  859.35  953.00  859.00  933.50  820.336942         NaN
170  2024-05-02  935.85  965.50  913.30  932.75  857.083248         NaN

In [845]:
df = stock
df['monthly_long'] = 0
df['monthly_long'] = np.where(pd.notna(df['Down Trend']), -1, df['monthly_long'])
df['monthly_long'] = np.where(pd.notna(df['Up Trend']), 1, df['monthly_long'])
df['monthly_long'] = df['monthly_long'].replace(0, np.nan)
df['monthly_long'] = df['monthly_long'].ffill()

df = df.rename(columns={'time': 'datetime', 'Up Trend': 'monthly_supertrend_green', 'Down Trend': 'monthly_supertrend_red'})
# df = df.drop(columns=['Up Trend.1', 'Down Trend.1'])

df['datetime'] = pd.to_datetime(df['datetime'])
df['datetime'] = df['datetime'].dt.tz_localize(None)

# df

In [846]:
df = df[(df['datetime'].dt.year >= 2017)]
df = df.reset_index()
df['indexer'] = df.index

In [847]:
df

,index,datetime,open,high,low,close,monthly_supertrend_green,monthly_supertrend_red,monthly_long,indexer
0,82,2017-01-02,69.65,84.65,69.05,80.20,NaN,91.992424,-1.0,0
1,83,2017-02-01,80.65,129.75,78.85,125.85,80.170223,NaN,1.0,1
2,84,2017-03-01,125.80,131.85,113.00,121.70,98.823201,NaN,1.0,2
3,85,2017-04-03,122.20,135.70,109.30,114.85,98.823201,NaN,1.0,3
4,86,2017-05-02,115.35,129.85,102.60,122.50,98.823201,NaN,1.0,4
5,87,2017-06-01,122.40,129.25,115.45,123.90,99.173388,NaN,1.0,5
6,88,2017-07-03,123.90,159.20,123.50,154.45,116.921050,NaN,1.0,6
7,89,2017-08-01,154.55,160.00,114.50,137.90,116.921050,NaN,1.0,7
8,90,2017-09-01,139.00,154.90,131.70,135.30,117.097550,NaN,1.0,8
9,91,2017-10-03,137.00,171.00,136.40,163.60,126.547795,NaN,1.0,9
10,92,2017-11-01,164.50,178.95,156.70,173.20,141.163016,NaN,1.0,10
11,93,2017-12-01,173.95,208.30,158.10,206.25,154.184214,NaN,1.0,11
12,94,2018-01-01,206.00,294.70,200.75,267.90,212.215793,NaN,1.0,12
13,95,2018-02-01,267.10,279.50,234.30,255.65,220.421713,NaN,1.0,13
14,96,2018-03-01,253.30,259.20,205.50,220.15,NaN,270.550458,-1.0,14
15,97,2018-04-02,223.80,264.40,218.10,253.60,NaN,270.550458,-1.0,15
16,98,2018-05-02,253.75,265.95,222.70,230.45,NaN,270.550458,-1.0,16
17,99,2018-06-01,229.40,251.00,209.80,223.90,NaN,270.010934,-1.0,17
18,100,2018-07-02,223.50,230.20,177.65,205.90,NaN,244.829840,-1.0,18
19,101,2018-08-01,209.85,229.20,189.25,222.25,NaN,244.829840,-1.0,19
20,102,2018-09-03,223.05,246.60,186.50,196.20,NaN,244.829840,-1.0,20
21,103,2018-10-01,191.05,199.20,157.15,172.20,NaN,220.844579,-1.0,21
22,104,2018-11-01,172.00,193.30,150.50,154.35,NaN,214.582621,-1.0,22
23,105,2018-12-03,159.00,173.00,140.80,165.70,NaN,198.534359,-1.0,23
24,106,2019-01-01,165.95,166.30,127.20,135.75,NaN,188.130923,-1.0,24
25,107,2019-02-01,135.50,164.55,123.50,157.85,NaN,185.372831,-1.0,25
26,108,2019-03-01,159.00,183.25,158.00,181.15,NaN,185.372831,-1.0,26
27,109,2019-04-01,184.45,192.10,166.95,178.75,NaN,185.372831,-1.0,27
28,110,2019-05-02,177.90,184.20,143.25,159.90,NaN,185.372831,-1.0,28
29,111,2019-06-03,159.50,171.40,137.00,143.10,NaN,185.372831,-1.0,29
30,112,2019-07-01,145.85,148.85,128.65,135.75,NaN,175.098359,-1.0,30
31,113,2019-08-01,134.40,134.40,91.20,97.20,NaN,149.968524,-1.0,31
32,114,2019-09-03,96.70,114.50,91.25,103.90,NaN,138.651671,-1.0,32
33,115,2019-10-01,104.80,119.95,91.45,116.65,NaN,138.651671,-1.0,33
34,116,2019-11-01,116.65,166.75,116.45,161.70,105.025896,NaN,1.0,34
35,117,2019-12-02,162.65,169.40,132.50,168.55,114.343307,NaN,1.0,35
36,118,2020-01-01,168.80,189.45,164.75,176.45,141.683976,NaN,1.0,36
37,119,2020-02-01,175.25,203.20,151.35,153.40,141.683976,NaN,1.0,37
38,120,2020-03-02,159.55,164.40,80.00,82.85,NaN,163.993479,-1.0,38
39,121,2020-04-01,82.60,97.80,62.15,95.35,NaN,121.154131,-1.0,39
40,122,2020-05-04,89.60,121.75,83.40,120.60,NaN,121.154131,-1.0,40
41,123,2020-06-01,122.45,165.00,122.45,161.65,102.478404,NaN,1.0,41
42,124,2020-07-01,163.15,187.00,152.10,185.50,128.938063,NaN,1.0,42
43,125,2020-08-03,185.35,238.90,183.75,205.65,169.259257,NaN,1.0,43
44,126,2020-09-01,206.85,227.00,159.60,187.00,169.259257,NaN,1.0,44
45,127,2020-10-01,188.75,214.40,180.65,191.60,169.259257,NaN,1.0,45
46,128,2020-11-02,192.60,253.40,187.30,245.25,174.577173,NaN,1.0,46
47,129,2020-12-01,248.05,287.80,244.20,267.60,220.444456,NaN,1.0,47
48,130,2021-01-01,269.00,311.45,259.00,262.15,238.980010,NaN,1.0,48
49,131,2021-02-01,263.45,349.50,258.00,337.30,252.979509,NaN,1.0,49
50,132,2021-03-01,339.95,357.00,297.80,346.05,275.786558,NaN,1.0,50
51,133,2021-04-01,348.00,462.20,348.00,443.35,347.032903,NaN,1.0,51
52,134,2021-05-03,439.65,504.00,383.10,409.45,379.199612,NaN,1.0,52
53,135,2021-06-01,411.40,429.80,364.60,398.55,379.199612,NaN,1.0,53
54,136,2021-07-01,401.10,448.35,378.30,433.45,379.199612,NaN,1.0,54
55,137,2021-08-02,434.10,436.55,357.10,378.35,NaN,461.635349,-1.0,55
56,138,2021-09-01,379.90,409.65,347.15,390.20,NaN,444.447919,-1.0,56
57,139,2021-10-01,386.00,473.20,379.85,417.70,NaN,444.447919,-1.0,57
58,140,2021-11-01,422.50,439.50,341.00,344.75,NaN,444.447919,-1.0,58
59,141,2021-12-01,352.15,409.00,344.15,378.75,NaN,444.447919,-1.0,59
60,142,2022-01-03,379.30,424.15,361.50,386.35,NaN,444.447919,-1.0,60
61,143,2022-02-01,389.95,446.00,368.30,425.70,NaN,444.447919,-1.0,61
62,144,2022-03-02,423.45,544.50,421.55,534.60,406.859404,NaN,1.0,62
63,145,2022-04-01,535.00,579.15,514.00,540.85,471.510963,NaN,1.0,63
64,146,2022-05-02,532.30,541.45,371.55,379.15,NaN,541.047633,-1.0,64
65,147,2022-06-01,381.90,387.10,303.90,327.55,NaN,429.912870,-1.0,65
66,148,2022-07-01,325.90,396.60,320.20,391.35,NaN,429.912870,-1.0,66
67,149,2022-08-01,392.85,434.50,372.40,433.10,321.989575,NaN,1.0,67
68,150,2022-09-01,426.40,468.00,385.75,430.90,345.335618,NaN,1.0,68
69,151,2022-10-03,427.95,474.00,418.30,461.15,367.194556,NaN,1.0,69
70,152,2022-11-01,454.15,543.85,454.15,538.95,418.970100,NaN,1.0,70
71,153,2022-12-01,542.55,599.50,523.55,584.65,481.903090,NaN,1.0,71
72,154,2023-01-02,587.20,615.50,568.20,588.70,515.460281,NaN,1.0,72
73,155,2023-02-01,583.75,627.10,547.50,552.90,515.460281,NaN,1.0,73
74,156,2023-03-01,555.95,595.30,530.60,549.85,515.460281,NaN,1.0,74
75,157,2023-04-03,550.00,591.40,540.25,584.70,515.460281,NaN,1.0,75
76,158,2023-05-02,588.50,607.75,507.00,521.35,515.460281,NaN,1.0,76
77,159,2023-06-01,522.80,606.65,511.05,585.20,515.460281,NaN,1.0,77
78,160,2023-07-03,584.85,679.75,583.80,674.15,552.144519,NaN,1.0,78
79,161,2023-08-01,675.55,702.00,631.90,688.25,588.272567,NaN,1.0,79
80,162,2023-09-01,689.40,724.75,679.85,705.90,627.000311,NaN,1.0,80
81,163,2023-10-03,703.95,706.85,631.00,636.40,627.000311,NaN,1.0,81
82,164,2023-11-01,620.00,679.35,585.60,676.30,627.000311,NaN,1.0,82
83,165,2023-12-01,682.00,772.15,675.05,753.55,644.415176,NaN,1.0,83
84,166,2024-01-01,754.00,769.25,686.70,762.70,648.453659,NaN,1.0,84
85,167,2024-02-01,769.00,807.50,709.00,780.20,676.830793,NaN,1.0,85
86,168,2024-03-01,781.85,868.65,760.50,853.20,730.482714,NaN,1.0,86
87,169,2024-04-01,859.35,953.00,859.00,933.50,820.336942,NaN,1.0,87
88,170,2024-05-02,935.85,965.50,913.30,932.75,857.083248,NaN,1.0,88

In [848]:
# def trade_high_break(stock_name):

#     in_trade = False
#     signal_active = False
#     entry_price = 0
#     exit_price = 0
#     signal_candle_high = 0
#     points = 0
#     remark = ''
#     initial_sl_pct = 3
#     target_pct = 15
#     portfolio_value = 5_00_000

#     tradebook = []
    
#     for i in range(0, len(df)):
        
#         if df.iloc[i]['monthly_long'] == 1 and df.iloc[i]['hourly_long'] == 1 and not in_trade:
#             #Signal Generated
#             if not signal_active:
#                 signal_active = True
#                 signal_time = df.iloc[i]['datetime']
#                 signal_candle_high = df.iloc[i]['high']
#             else:
#                 if df.iloc[i]['high'] < df.iloc[i-1]['high']:
#                     #Better Candle Formed
#                     signal_time = df.iloc[i]['datetime']
#                     signal_candle_high = df.iloc[i]['high']
            
#         if signal_active and not in_trade:
#             if df.iloc[i]['high'] > signal_candle_high:
#                 # Entry Triggered
#                 # print(df.iloc[i]['datetime'] , 'Entry Triggered' , signal_candle_high)
#                 in_trade = True
#                 entry_price = signal_candle_high
#                 entry_time = df.iloc[i]['datetime']
#                 initial_sl = entry_price * (1 - (initial_sl_pct / 100))
#                 initial_target = entry_price * (1 + (target_pct / 100))
#                 continue

#         if in_trade:
#             if df.iloc[i]['hourly_long'] == 0:
#                 # Supertrend reversed, SL hit
#                 # print(df.iloc[i]['datetime'] , 'Exited Trade' , df.iloc[i]['low'])
#                 exit_price = df.iloc[i]['close']
#                 exit_time = df.iloc[i]['datetime']
#                 in_trade = False
#                 signal_active = False
#                 points = exit_price - entry_price
#                 remark = 'SuperTrend Reversed'

#             elif df.iloc[i]['low'] < initial_sl:
#                 #Initial SL hit
                
#                 if df.iloc[i]['open'] < initial_sl:
#                     #Gapped below Initial SL, exit at open
#                     exit_price = initial_sl
#                     exit_time = df.iloc[i]['datetime']
#                     remark = 'Gapped Outside Initial SL'

#                 else:
#                     exit_price = initial_sl
#                     exit_time = df.iloc[i]['datetime']
#                     remark = 'Initial SL Hit'
                    
#                 in_trade = False
#                 signal_active = False
#                 points = exit_price - entry_price

#             elif df.iloc[i]['high'] > initial_target:
#                 # Target Hit
#                 exit_price = initial_target
#                 exit_time = df.iloc[i]['datetime']
#                 in_trade = False
#                 signal_active = False
#                 points = exit_price - entry_price
#                 remark = 'Target Hit'

#         if points:
            
#             qty = portfolio_value / entry_price
#             slippage = 0.001 * (entry_price + exit_price)
#             final_points = points - slippage
            
#             trade = {
#                 'Signal Generated At': signal_time,
#                 'Stock Name': stock_name,
#                 'Entry Date': entry_time.date(),
#                 'Entry Time': entry_time.time(),
#                 'Entry Price': entry_price,
#                 'Initial SL': initial_sl,
#                 'Initial Target': initial_target,
#                 'Exit Date': exit_time.date(),
#                 'Exit Time': exit_time.time(),
#                 'Exit Price': exit_price,
#                 'Remark': remark,
#                 'Points Captured': points,
#                 'After Costs': final_points,
#                 'Qty': qty,
#                 'PnL': final_points * qty,
#                 'ROI%': (final_points * qty / portfolio_value) * 100,
#                 'Trade Year': entry_time.year,
#                 'Trade Month': entry_time.month
#                 }
#             tradebook.append(trade)
#             entry_price = 0
#             exit_price = 0
#             points = 0
#             remark = ''
#             in_trade = False
#             signal_active = False

#     return tradebook

In [849]:
# def trade_next_open(stock_name):

#     in_trade = False
#     # signal_active = False
#     entry_price = 0
#     exit_price = 0
#     signal_candle_high = 0
#     points = 0
#     remark = ''
#     initial_sl_pct = 100
#     target_pct = 1500
#     portfolio_value = 5_00_000

#     tradebook = []
    
#     for i in range(0, len(df)):
        
#         if (df.iloc[i]['monthly_long'] == 1) and (df.iloc[i-1]['monthly_long'] == 1) and not in_trade:
#             #Entry Triggered
#             in_trade = True
#             entry_price = df.iloc[i]['open']
#             entry_time = df.iloc[i]['datetime']
#             initial_sl = entry_price * (1 - (initial_sl_pct / 100))
#             initial_target = entry_price * (1 + (target_pct / 100))
    
#             print('Entry Triggered ! ', df.iloc[i]['datetime'])

#             continue

#             #TODO : Try using the nearer SL between low of entry candle and initial_sl fixed for Initial SL of the trade
#             # ----> initial_sl = max( df.iloc[i]['low'] , entry_price * (1 - (initial_sl_pct / 100)) )
            
#         if in_trade:
#             if df.iloc[i]['monthly_long'] == -1:
#                 # Supertrend reversed, SL hit
#                 # print(df.iloc[i]['datetime'] , 'Exited Trade' , df.iloc[i]['low'])
#                 exit_price = df.iloc[i]['close']
#                 exit_time = df.iloc[i]['datetime']
#                 in_trade = False
#                 # signal_active = False
                
#                 points = exit_price - entry_price
#                 remark = 'SuperTrend Reversed'
#                 print(remark, df.iloc[i]['datetime'])

#             elif df.iloc[i]['low'] < initial_sl:
#                 #Initial SL hit
                
#                 if df.iloc[i]['open'] < initial_sl:
#                     #Gapped below Initial SL, exit at open
#                     exit_price = initial_sl
#                     exit_time = df.iloc[i]['datetime']
#                     remark = 'Gapped Outside Initial SL'
#                     print(remark, df.iloc[i]['datetime'])

#                 else:
#                     exit_price = initial_sl
#                     exit_time = df.iloc[i]['datetime']
#                     remark = 'Initial SL Hit'
#                     print(remark, df.iloc[i]['datetime'])
                    
#                 in_trade = False
#                 # signal_active = False
#                 points = exit_price - entry_price

#             elif df.iloc[i]['high'] > initial_target:
#                 # Target Hit
#                 exit_price = initial_target
#                 exit_time = df.iloc[i]['datetime']
#                 in_trade = False
#                 # signal_active = False
#                 points = exit_price - entry_price
#                 remark = 'Target Hit'
#                 print(remark, df.iloc[i]['datetime'])

#         if points:
            
#             qty = portfolio_value / entry_price
#             slippage = 0.001 * (entry_price + exit_price)
#             final_points = points - slippage
            
#             trade = {
#                 'Stock Name': stock_name,
#                 'Entry Date': entry_time.date(),
#                 'Entry Price': entry_price,
#                 'Initial SL': initial_sl,
#                 'Initial Target': initial_target,
#                 'Exit Date': exit_time.date(),
#                 'Exit Price': exit_price,
#                 'Remark': remark,
#                 'Points Captured': points,
#                 'After Costs': final_points,
#                 'Qty': qty,
#                 'PnL': final_points * qty,
#                 'ROI%': (final_points * qty / portfolio_value) * 100,
#                 'Trade Year': entry_time.year,
#                 'Trade Month': entry_time.month
#                 }
#             tradebook.append(trade)
#             entry_price = 0
#             exit_price = 0
#             points = 0
#             remark = ''
#             in_trade = False
#             # signal_active = False

#     return tradebook

In [850]:
# tb = trade_next_open(current_stock)
# tb_pandas = pd.DataFrame(tb)
# # tb_pandas

In [851]:
# tb_pandas

In [852]:
# roi = tb_pandas['ROI%'].sum()
# roi

In [853]:
# def stats(stock_name, df):
#     print(stock_name)
#     stats = pd.DataFrame(index=range(2012, 2025), columns=['Total ROI', 'Total Trades', 'Win Rate', 'Avg Profit% per Trade', 'Avg Loss% per Trade', 'Max Drawdown', 'ROI/DD Ratio'])
    
#     # Iterate over each year
#     for year in range(2012, 2025):
#         # Filter trades for the current year
#         year_trades = df[(df['Trade Year'] == year)]
        
#         # Calculate total ROI
#         total_roi = year_trades['ROI%'].sum()
        
#         # Calculate total number of trades
#         total_trades = len(year_trades)
        
#         # Calculate win rate
#         win_rate = (year_trades['ROI%'] > 0).mean()*100
        
#         # Calculate average profit per trade
#         avg_profit = year_trades[year_trades['ROI%'] > 0]['ROI%'].mean()
        
#         # Calculate average loss per trade
#         avg_loss = year_trades[year_trades['ROI%'] < 0]['ROI%'].mean()
        
#         # Calculate maximum drawdown
#         max_drawdown = (year_trades['ROI%'].cumsum() - year_trades['ROI%'].cumsum().cummax()).min()
        
#         # Calculate ROI/DD ratio
#         roi_dd_ratio = total_roi / abs(max_drawdown)
        
#         # Store the statistics in the DataFrame
#         stats.loc[year] = [total_roi, total_trades, win_rate, avg_profit, avg_loss, max_drawdown, roi_dd_ratio]
    
#     # Calculate overall statistics
#     overall_total_roi = stats['Total ROI'].sum()
#     overall_total_trades = stats['Total Trades'].sum()
#     overall_win_rate = (df['ROI%'] > 0).mean() * 100
#     overall_avg_profit = df[df['ROI%'] > 0]['ROI%'].mean()
#     overall_avg_loss = df[df['ROI%'] < 0]['ROI%'].mean()
#     overall_max_drawdown = (df['ROI%'].cumsum() - df['ROI%'].cumsum().cummax()).min()
#     overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)
    
#     # Store the overall statistics in the DataFrame
#     stats.loc['Overall'] = [overall_total_roi, overall_total_trades, overall_win_rate, overall_avg_profit, overall_avg_loss, overall_max_drawdown, overall_roi_dd_ratio]
#     return stats

# results = stats(current_stock, tb_pandas)
# results

In [854]:
# tradebook_name = f'{current_stock}_stonks_v2_tradebook.csv'
# tb_pandas.to_csv(tradebook_name)

In [855]:
from datetime import timedelta

def trade_next_open_monthly_long(stock_name, df):
    in_trade = False
    entry_price = 0
    exit_price = 0
    signal_candle_high = 0
    points = 0
    remark = ''
    initial_sl_pct = 100
    target_pct = 1500
    portfolio_value = 10_00_000
    trade_number = 1

    tradebook = []
    
    for i in range(0, len(df)):
        
        if (df.iloc[i]['monthly_long'] == 1) and not in_trade:
            #Entry Triggered
            in_trade = True
            entry_price = df.iloc[i]['close']
            entry_time = df.iloc[i]['datetime']
            initial_sl = entry_price * (1 - (initial_sl_pct / 100))
            initial_target = entry_price * (1 + (target_pct / 100))
    
            # print('Entry Triggered ! ', df.iloc[i]['datetime'])

            continue

            #TODO : Try using the nearer SL between low of entry candle and initial_sl fixed for Initial SL of the trade
            # ----> initial_sl = max( df.iloc[i]['low'] , entry_price * (1 - (initial_sl_pct / 100)) )
            
        if in_trade:
            if df.iloc[i]['monthly_long'] == -1:
                # Supertrend reversed, SL hit
                exit_price = df.iloc[i]['close']
                exit_time = df.iloc[i]['datetime']
                in_trade = False
                points = exit_price - entry_price
                remark = 'SuperTrend Reversed'
                # print(remark, df.iloc[i]['datetime'])

            elif df.iloc[i]['low'] < initial_sl:
                #Initial SL hit
                
                if df.iloc[i]['open'] < initial_sl:
                    #Gapped below Initial SL, exit at open
                    exit_price = df.iloc[i]['open']
                    exit_time = df.iloc[i]['datetime']
                    remark = 'Gapped Outside Initial SL'
                    # print(remark, df.iloc[i]['datetime'])

                else:
                    exit_price = initial_sl
                    exit_time = df.iloc[i]['datetime']
                    remark = 'Initial SL Hit'
                    print(remark, df.iloc[i]['datetime'])
                    
                in_trade = False
                points = exit_price - entry_price

            elif df.iloc[i]['high'] > initial_target:
                # Target Hit
                exit_price = initial_target
                exit_time = df.iloc[i]['datetime']
                in_trade = False
                points = exit_price - entry_price
                remark = 'Target Hit'
                # print(remark, df.iloc[i]['datetime'])

            elif df.iloc[i]['indexer'] == df.iloc[-1]['indexer']:
                # Ending Currently Active Trade
                exit_price = df.iloc[i]['close']
                exit_time = df.iloc[i]['datetime']
                in_trade = False
                points = exit_price - entry_price
                remark = 'Currently Active Trade'
                # print(remark, df.iloc[i]['datetime'])

        if points:
            # Calculate PnL for the whole trade duration
            qty = portfolio_value / entry_price
            slippage = 0.001 * (entry_price + exit_price)
            # final_points = points - slippage
            
            trade_duration = (exit_time - entry_time)

            st_index = df.loc[df['datetime'] == entry_time, 'indexer'].iloc[0]
            en_index = df.loc[df['datetime'] == exit_time, 'indexer'].iloc[0]
            current_index = df.loc[df['datetime'] == entry_time, 'indexer'].iloc[0]
            st_index += 1
            while current_index < en_index:
                trade = {
                    'Stock Name': stock_name,
                    'Trade Type': 'LONG',
                    'Entry Date': df.iloc[current_index]['datetime'],
                    'Entry Price': df.iloc[current_index]['close'],
                    'Exit Date': df.iloc[st_index]['datetime'],
                    'Exit Price': df.iloc[st_index]['close'],
                    'Points Captured': df.iloc[st_index]['close'] - df.iloc[current_index]['close'],
                    'Qty': qty,
                    'PnL': (df.loc[st_index]['close'] - df.iloc[current_index]['close']) * qty,
                    'ROI%': ((df.loc[st_index]['close'] - df.iloc[current_index]['close']) * qty / portfolio_value) * 100,
                    'Pct Change on Stock': ((df.loc[st_index]['close'] - df.iloc[current_index]['close']) / df.loc[current_index]['close']) * 100,
                    'Trade Year': entry_time.year,
                    'Trade Number': f'{trade_number}L',
                }
                # print(trade)
                current_index += 1
                st_index += 1
    
                tradebook.append(trade)
            trade_number += 1
                
            entry_price = 0
            exit_price = 0
            points = 0
            remark = ''
            in_trade = False

    return pd.DataFrame(tradebook)

In [856]:
from datetime import timedelta

def trade_next_open_monthly_short(stock_name, df):
    in_trade = False
    entry_price = 0
    exit_price = 0
    signal_candle_high = 0
    points = 0
    remark = ''
    initial_sl_pct = 100
    target_pct = 1500
    portfolio_value = 10_00_000
    trade_number = 1

    tradebook = []
    
    for i in range(0, len(df)):
        
        if (df.iloc[i]['monthly_long'] == -1) and not in_trade:
            #Entry Triggered
            in_trade = True
            entry_price = df.iloc[i]['close']
            entry_time = df.iloc[i]['datetime']
            initial_sl = entry_price * (1 + (initial_sl_pct / 100))
            initial_target = entry_price * (1 - (target_pct / 100))
    
            # print('Entry Triggered ! ', df.iloc[i]['datetime'])

            continue

            #TODO : Try using the nearer SL between low of entry candle and initial_sl fixed for Initial SL of the trade
            # ----> initial_sl = max( df.iloc[i]['low'] , entry_price * (1 - (initial_sl_pct / 100)) )
            
        if in_trade:
            if df.iloc[i]['monthly_long'] == 1:
                # Supertrend reversed, SL hit
                exit_price = df.iloc[i]['close']
                exit_time = df.iloc[i]['datetime']
                in_trade = False
                points = entry_price - exit_price
                remark = 'SuperTrend Reversed'
                # print(remark, df.iloc[i]['datetime'])

            elif df.iloc[i]['high'] > initial_sl:
                #Initial SL hit
                
                if df.iloc[i]['open'] > initial_sl:
                    #Gapped above Initial SL, exit at open
                    exit_price = df.iloc[i]['open']
                    exit_time = df.iloc[i]['datetime']
                    remark = 'Gapped Outside Initial SL'
                    # print(remark, df.iloc[i]['datetime'])

                else:
                    exit_price = initial_sl
                    exit_time = df.iloc[i]['datetime']
                    remark = 'Initial SL Hit'
                    print(remark, df.iloc[i]['datetime'])
                    
                in_trade = False
                points = entry_price - exit_price

            elif df.iloc[i]['low'] < initial_target:
                # Target Hit
                exit_price = initial_target
                exit_time = df.iloc[i]['datetime']
                in_trade = False
                points = entry_price - exit_price
                remark = 'Target Hit'
                # print(remark, df.iloc[i]['datetime'])

            elif df.iloc[i]['indexer'] == df.iloc[-1]['indexer']:
                # Ending Currently Active Trade
                exit_price = df.iloc[i]['close']
                exit_time = df.iloc[i]['datetime']
                in_trade = False
                points = entry_price - exit_price
                remark = 'Currently Active Trade'
                # print(remark, df.iloc[i]['datetime'])

        if points:
            # Calculate PnL for the whole trade duration
            qty = portfolio_value / entry_price
            slippage = 0.001 * (entry_price + exit_price)
            # final_points = points - slippage
            
            trade_duration = (exit_time - entry_time)

            st_index = df.loc[df['datetime'] == entry_time, 'indexer'].iloc[0]
            en_index = df.loc[df['datetime'] == exit_time, 'indexer'].iloc[0]
            current_index = df.loc[df['datetime'] == entry_time, 'indexer'].iloc[0]
            st_index += 1
            while current_index < en_index:
                trade = {
                    'Stock Name': stock_name,
                    'Trade Type': 'SHORT',
                    'Entry Date': df.iloc[current_index]['datetime'],
                    'Entry Price': df.iloc[current_index]['close'],
                    'Exit Date': df.iloc[st_index]['datetime'],
                    'Exit Price': df.iloc[st_index]['close'],
                    'Points Captured': df.iloc[current_index]['close'] - df.iloc[st_index]['close'],
                    'Qty': qty,
                    'PnL': (df.loc[current_index]['close'] - df.iloc[st_index]['close']) * qty,
                    'ROI%': ((df.loc[current_index]['close'] - df.iloc[st_index]['close']) * qty / portfolio_value) * 100,
                    'Pct Change on Stock': ((df.loc[st_index]['close'] - df.iloc[current_index]['close']) / df.loc[current_index]['close']) * 100,
                    'Trade Year': entry_time.year,
                    'Trade Number': f'{trade_number}S',
                }
                # print(trade)
                current_index += 1
                st_index += 1
    
                tradebook.append(trade)
            trade_number += 1
                
            entry_price = 0
            exit_price = 0
            points = 0
            remark = ''
            in_trade = False

    return pd.DataFrame(tradebook)

In [857]:
tb_per_month_long = trade_next_open_monthly_long(current_stock, df)
tb_per_month_short = trade_next_open_monthly_short(current_stock, df)
final_tb = pd.concat([tb_per_month_long, tb_per_month_short], ignore_index=True)
final_tb = final_tb.sort_values(by='Entry Date')
tb_pandas_per_month = pd.DataFrame(final_tb)
# tb_pandas_per_month = tb_pandas_per_month.iloc[1:]
# tb_pandas_per_month.reset_index(drop=True, inplace=True)
tb_pandas_per_month

,Stock Name,Trade Type,Entry Date,Entry Price,Exit Date,Exit Price,Points Captured,Qty,PnL,ROI%,Pct Change on Stock,Trade Year,Trade Number
54,JINDALSTEL,SHORT,2017-01-02,80.20,2017-02-01,125.85,-45.65,12468.827930,-569201.995012,-56.920200,56.920200,2017,1S
0,JINDALSTEL,LONG,2017-02-01,125.85,2017-03-01,121.70,-4.15,7945.967422,-32975.764799,-3.297576,-3.297576,2017,1L
1,JINDALSTEL,LONG,2017-03-01,121.70,2017-04-03,114.85,-6.85,7945.967422,-54429.876838,-5.442988,-5.628595,2017,1L
2,JINDALSTEL,LONG,2017-04-03,114.85,2017-05-02,122.50,7.65,7945.967422,60786.650775,6.078665,6.660862,2017,1L
3,JINDALSTEL,LONG,2017-05-02,122.50,2017-06-01,123.90,1.40,7945.967422,11124.354390,1.112435,1.142857,2017,1L
4,JINDALSTEL,LONG,2017-06-01,123.90,2017-07-03,154.45,30.55,7945.967422,242749.304728,24.274930,24.656981,2017,1L
5,JINDALSTEL,LONG,2017-07-03,154.45,2017-08-01,137.90,-16.55,7945.967422,-131505.760826,-13.150576,-10.715442,2017,1L
6,JINDALSTEL,LONG,2017-08-01,137.90,2017-09-01,135.30,-2.60,7945.967422,-20659.515296,-2.065952,-1.885424,2017,1L
7,JINDALSTEL,LONG,2017-09-01,135.30,2017-10-03,163.60,28.30,7945.967422,224870.878029,22.487088,20.916482,2017,1L
8,JINDALSTEL,LONG,2017-10-03,163.60,2017-11-01,173.20,9.60,7945.967422,76281.287247,7.628129,5.867971,2017,1L
9,JINDALSTEL,LONG,2017-11-01,173.20,2017-12-01,206.25,33.05,7945.967422,262614.223282,26.261422,19.081986,2017,1L
10,JINDALSTEL,LONG,2017-12-01,206.25,2018-01-01,267.90,61.65,7945.967422,489868.891538,48.986889,29.890909,2017,1L
11,JINDALSTEL,LONG,2018-01-01,267.90,2018-02-01,255.65,-12.25,7945.967422,-97338.100914,-9.733810,-4.572602,2017,1L
12,JINDALSTEL,LONG,2018-02-01,255.65,2018-03-01,220.15,-35.50,7945.967422,-282081.843464,-28.208184,-13.886173,2017,1L
55,JINDALSTEL,SHORT,2018-03-01,220.15,2018-04-02,253.60,-33.45,4542.357484,-151941.857824,-15.194186,15.194186,2018,2S
56,JINDALSTEL,SHORT,2018-04-02,253.60,2018-05-02,230.45,23.15,4542.357484,105155.575744,10.515558,-9.128549,2018,2S
57,JINDALSTEL,SHORT,2018-05-02,230.45,2018-06-01,223.90,6.55,4542.357484,29752.441517,2.975244,-2.842265,2018,2S
58,JINDALSTEL,SHORT,2018-06-01,223.90,2018-07-02,205.90,18.00,4542.357484,81762.434704,8.176243,-8.039303,2018,2S
59,JINDALSTEL,SHORT,2018-07-02,205.90,2018-08-01,222.25,-16.35,4542.357484,-74267.544856,-7.426754,7.940748,2018,2S
60,JINDALSTEL,SHORT,2018-08-01,222.25,2018-09-03,196.20,26.05,4542.357484,118328.412446,11.832841,-11.721035,2018,2S
61,JINDALSTEL,SHORT,2018-09-03,196.20,2018-10-01,172.20,24.00,4542.357484,109016.579605,10.901658,-12.232416,2018,2S
62,JINDALSTEL,SHORT,2018-10-01,172.20,2018-11-01,154.35,17.85,4542.357484,81081.081081,8.108108,-10.365854,2018,2S
63,JINDALSTEL,SHORT,2018-11-01,154.35,2018-12-03,165.70,-11.35,4542.357484,-51555.757438,-5.155576,7.353418,2018,2S
64,JINDALSTEL,SHORT,2018-12-03,165.70,2019-01-01,135.75,29.95,4542.357484,136043.606632,13.604361,-18.074834,2018,2S
65,JINDALSTEL,SHORT,2019-01-01,135.75,2019-02-01,157.85,-22.10,4542.357484,-100386.100386,-10.038610,16.279926,2018,2S
66,JINDALSTEL,SHORT,2019-02-01,157.85,2019-03-01,181.15,-23.30,4542.357484,-105836.929366,-10.583693,14.760849,2018,2S
67,JINDALSTEL,SHORT,2019-03-01,181.15,2019-04-01,178.75,2.40,4542.357484,10901.657960,1.090166,-1.324869,2018,2S
68,JINDALSTEL,SHORT,2019-04-01,178.75,2019-05-02,159.90,18.85,4542.357484,85623.438565,8.562344,-10.545455,2018,2S
69,JINDALSTEL,SHORT,2019-05-02,159.90,2019-06-03,143.10,16.80,4542.357484,76311.605723,7.631161,-10.506567,2018,2S
70,JINDALSTEL,SHORT,2019-06-03,143.10,2019-07-01,135.75,7.35,4542.357484,33386.327504,3.338633,-5.136268,2018,2S
71,JINDALSTEL,SHORT,2019-07-01,135.75,2019-08-01,97.20,38.55,4542.357484,175107.880990,17.510788,-28.397790,2018,2S
72,JINDALSTEL,SHORT,2019-08-01,97.20,2019-09-03,103.90,-6.70,4542.357484,-30433.795140,-3.043380,6.893004,2018,2S
73,JINDALSTEL,SHORT,2019-09-03,103.90,2019-10-01,116.65,-12.75,4542.357484,-57915.057915,-5.791506,12.271415,2018,2S
74,JINDALSTEL,SHORT,2019-10-01,116.65,2019-11-01,161.70,-45.05,4542.357484,-204633.204633,-20.463320,38.619803,2018,2S
13,JINDALSTEL,LONG,2019-11-01,161.70,2019-12-02,168.55,6.85,6184.291899,42362.399505,4.236240,4.236240,2019,2L
14,JINDALSTEL,LONG,2019-12-02,168.55,2020-01-01,176.45,7.90,6184.291899,48855.905999,4.885591,4.687036,2019,2L
15,JINDALSTEL,LONG,2020-01-01,176.45,2020-02-01,153.40,-23.05,6184.291899,-142547.928262,-14.254793,-13.063191,2019,2L
16,JINDALSTEL,LONG,2020-02-01,153.40,2020-03-02,82.85,-70.55,6184.291899,-436301.793445,-43.630179,-45.990874,2019,2L
75,JINDALSTEL,SHORT,2020-03-02,82.85,2020-04-01,95.35,-12.50,12070.006035,-150875.075438,-15.087508,15.087508,2020,3S
76,JINDALSTEL,SHORT,2020-04-01,95.35,2020-05-04,120.60,-25.25,12070.006035,-304767.652384,-30.476765,26.481384,2020,3S
77,JINDALSTEL,SHORT,2020-05-04,120.60,2020-06-01,161.65,-41.05,12070.006035,-495473.747737,-49.547375,34.038143,2020,3S
17,JINDALSTEL,LONG,2020-06-01,161.65,2020-07-01,185.50,23.85,6186.204763,147540.983607,14.754098,14.754098,2020,3L
18,JINDALSTEL,LONG,2020-07-01,185.50,2020-08-03,205.65,20.15,6186.204763,124652.025982,12.465203,10.862534,2020,3L
19,JINDALSTEL,LONG,2020-08-03,205.65,2020-09-01,187.00,-18.65,6186.204763,-115372.718837,-11.537272,-9.068806,2020,3L
20,JINDALSTEL,LONG,2020-09-01,187.00,2020-10-01,191.60,4.60,6186.204763,28456.541912,2.845654,2.459893,2020,3L
21,JINDALSTEL,LONG,2020-10-01,191.60,2020-11-02,245.25,53.65,6186.204763,331889.885555,33.188989,28.001044,2020,3L
22,JINDALSTEL,LONG,2020-11-02,245.25,2020-12-01,267.60,22.35,6186.204763,138261.676461,13.826168,9.113150,2020,3L
23,JINDALSTEL,LONG,2020-12-01,267.60,2021-01-01,262.15,-5.45,6186.204763,-33714.815960,-3.371482,-2.036622,2020,3L
24,JINDALSTEL,LONG,2021-01-01,262.15,2021-02-01,337.30,75.15,6186.204763,464893.287968,46.489329,28.666794,2020,3L
25,JINDALSTEL,LONG,2021-02-01,337.30,2021-03-01,346.05,8.75,6186.204763,54129.291680,5.412929,2.594130,2020,3L
26,JINDALSTEL,LONG,2021-03-01,346.05,2021-04-01,443.35,97.30,6186.204763,601917.723477,60.191772,28.117324,2020,3L
27,JINDALSTEL,LONG,2021-04-01,443.35,2021-05-03,409.45,-33.90,6186.204763,-209712.341479,-20.971234,-7.646329,2020,3L
28,JINDALSTEL,LONG,2021-05-03,409.45,2021-06-01,398.55,-10.90,6186.204763,-67429.631921,-6.742963,-2.662108,2020,3L
29,JINDALSTEL,LONG,2021-06-01,398.55,2021-07-01,433.45,34.90,6186.204763,215898.546242,21.589855,8.756743,2020,3L
30,JINDALSTEL,LONG,2021-07-01,433.45,2021-08-02,378.35,-55.10,6186.204763,-340859.882462,-34.085988,-12.711962,2020,3L
78,JINDALSTEL,SHORT,2021-08-02,378.35,2021-09-01,390.20,-11.85,2643.055372,-31320.206158,-3.132021,3.132021,2021,4S
79,JINDALSTEL,SHORT,2021-09-01,390.20,2021-10-01,417.70,-27.50,2643.055372,-72684.022730,-7.268402,7.047668,2021,4S
80,JINDALSTEL,SHORT,2021-10-01,417.70,2021-11-01,344.75,72.95,2643.055372,192810.889388,19.281089,-17.464688,2021,4S
81,JINDALSTEL,SHORT,2021-11-01,344.75,2021-12-01,378.75,-34.00,2643.055372,-89863.882648,-8.986388,9.862219,2021,4S
82,JINDALSTEL,SHORT,2021-12-01,378.75,2022-01-03,386.35,-7.60,2643.055372,-20087.220827,-2.008722,2.006601,2021,4S
83,JINDALSTEL,SHORT,2022-01-03,386.35,2022-02-01,425.70,-39.35,2643.055372,-104004.228889,-10.400423,10.185065,2021,4S
84,JINDALSTEL,SHORT,2022-02-01,425.70,2022-03-02,534.60,-108.90,2643.055372,-287828.730012,-28.782873,25.581395,2021,4S
31,JINDALSTEL,LONG,2022-03-02,534.60,2022-04-01,540.85,6.25,1870.557426,11690.983913,1.169098,1.169098,2022,4L
32,JINDALSTEL,LONG,2022-04-01,540.85,2022-05-02,379.15,-161.70,1870.557426,-302469.135802,-30.246914,-29.897384,2022,4L
85,JINDALSTEL,SHORT,2022-05-02,379.15,2022-06-01,327.55,51.60,2637.478570,136093.894237,13.609389,-13.609389,2022,5S
86,JINDALSTEL,SHORT,2022-06-01,327.55,2022-07-01,391.35,-63.80,2637.478570,-168271.132797,-16.827113,19.477942,2022,5S
87,JINDALSTEL,SHORT,2022-07-01,391.35,2022-08-01,433.10,-41.75,2637.478570,-110114.730318,-11.011473,10.668200,2022,5S
33,JINDALSTEL,LONG,2022-08-01,433.10,2022-09-01,430.90,-2.20,2308.935581,-5079.658278,-0.507966,-0.507966,2022,5L
34,JINDALSTEL,LONG,2022-09-01,430.90,2022-10-03,461.15,30.25,2308.935581,69845.301316,6.984530,7.020190,2022,5L
35,JINDALSTEL,LONG,2022-10-03,461.15,2022-11-01,538.95,77.80,2308.935581,179635.188178,17.963519,16.870866,2022,5L
36,JINDALSTEL,LONG,2022-11-01,538.95,2022-12-01,584.65,45.70,2308.935581,105518.356038,10.551836,8.479451,2022,5L
37,JINDALSTEL,LONG,2022-12-01,584.65,2023-01-02,588.70,4.05,2308.935581,9351.189102,0.935119,0.692722,2022,5L
38,JINDALSTEL,LONG,2023-01-02,588.70,2023-02-01,552.90,-35.80,2308.935581,-82659.893789,-8.265989,-6.081196,2022,5L
39,JINDALSTEL,LONG,2023-02-01,552.90,2023-03-01,549.85,-3.05,2308.935581,-7042.253521,-0.704225,-0.551637,2022,5L
40,JINDALSTEL,LONG,2023-03-01,549.85,2023-04-03,584.70,34.85,2308.935581,80466.404987,8.046640,6.338092,2022,5L
41,JINDALSTEL,LONG,2023-04-03,584.70,2023-05-02,521.35,-63.35,2308.935581,-146271.069037,-14.627107,-10.834616,2022,5L
42,JINDALSTEL,LONG,2023-05-02,521.35,2023-06-01,585.20,63.85,2308.935581,147425.536828,14.742554,12.247051,2022,5L
43,JINDALSTEL,LONG,2023-06-01,585.20,2023-07-03,674.15,88.95,2308.935581,205379.819903,20.537982,15.199932,2022,5L
44,JINDALSTEL,LONG,2023-07-03,674.15,2023-08-01,688.25,14.10,2308.935581,32555.991688,3.255599,2.091523,2022,5L
45,JINDALSTEL,LONG,2023-08-01,688.25,2023-09-01,705.90,17.65,2308.935581,40752.712999,4.075271,2.564475,2022,5L
46,JINDALSTEL,LONG,2023-09-01,705.90,2023-10-03,636.40,-69.50,2308.935581,-160471.022858,-16.047102,-9.845587,2022,5L
47,JINDALSTEL,LONG,2023-10-03,636.40,2023-11-01,676.30,39.90,2308.935581,92126.529670,9.212653,6.269642,2022,5L
48,JINDALSTEL,LONG,2023-11-01,676.30,2023-12-01,753.55,77.25,2308.935581,178365.273609,17.836527,11.422446,2022,5L
49,JINDALSTEL,LONG,2023-12-01,753.55,2024-01-01,762.70,9.15,2308.935581,21126.760563,2.112676,1.214253,2022,5L
50,JINDALSTEL,LONG,2024-01-01,762.70,2024-02-01,780.20,17.50,2308.935581,40406.372662,4.040637,2.294480,2022,5L
51,JINDALSTEL,LONG,2024-02-01,780.20,2024-03-01,853.20,73.00,2308.935581,168552.297391,16.855230,9.356575,2022,5L
52,JINDALSTEL,LONG,2024-03-01,853.20,2024-04-01,933.50,80.30,2308.935581,185407.527130,18.540753,9.411627,2022,5L
53,JINDALSTEL,LONG,2024-04-01,933.50,2024-05-02,932.75,-0.75,2308.935581,-1731.701686,-0.173170,-0.080343,2022,5L

In [858]:
def stats(stock_name, df):
    print(stock_name)
    stats = pd.DataFrame(index=range(2012, 2025), columns=['Total ROI', 'Total Trades', 'Win Rate', 'Avg Profit% per Trade', 'Avg Loss% per Trade', 'Max Drawdown', 'ROI/DD Ratio'])
    
    # Iterate over each year
    for year in range(2012, 2025):
        # Filter trades for the current year
        year_trades = df[(df['Trade Year'] == year)]
        
        # Calculate total ROI
        total_roi = year_trades['ROI%'].sum()
        
        # Calculate total number of trades
        total_trades = len(year_trades)
        
        # Calculate win rate
        win_rate = (year_trades['ROI%'] > 0).mean()*100
        
        # Calculate average profit per trade
        avg_profit = year_trades[year_trades['ROI%'] > 0]['ROI%'].mean()
        
        # Calculate average loss per trade
        avg_loss = year_trades[year_trades['ROI%'] < 0]['ROI%'].mean()
        
        # Calculate maximum drawdown
        max_drawdown = (year_trades['ROI%'].cumsum() - year_trades['ROI%'].cumsum().cummax()).min()
        
        # Calculate ROI/DD ratio
        roi_dd_ratio = total_roi / abs(max_drawdown)
        
        # Store the statistics in the DataFrame
        stats.loc[year] = [total_roi, total_trades, win_rate, avg_profit, avg_loss, max_drawdown, roi_dd_ratio]
    
    # Calculate overall statistics
    overall_total_roi = stats['Total ROI'].sum()
    overall_total_trades = stats['Total Trades'].sum()
    overall_win_rate = (df['ROI%'] > 0).mean() * 100
    overall_avg_profit = df[df['ROI%'] > 0]['ROI%'].mean()
    overall_avg_loss = df[df['ROI%'] < 0]['ROI%'].mean()
    overall_max_drawdown = (df['ROI%'].cumsum() - df['ROI%'].cumsum().cummax()).min()
    overall_roi_dd_ratio = overall_total_roi / abs(overall_max_drawdown)
    
    # Store the overall statistics in the DataFrame
    stats.loc['Overall'] = [overall_total_roi, overall_total_trades, overall_win_rate, overall_avg_profit, overall_avg_loss, overall_max_drawdown, overall_roi_dd_ratio]
    return stats

results = stats(current_stock, tb_pandas_per_month)
results

JINDALSTEL

,Total ROI,Total Trades,Win Rate,Avg Profit% per Trade,Avg Loss% per Trade,Max Drawdown,ROI/DD Ratio
2012,0.0,0,NaN,NaN,NaN,NaN,NaN
2013,0.0,0,NaN,NaN,NaN,NaN,NaN
2014,0.0,0,NaN,NaN,NaN,NaN,NaN
2015,0.0,0,NaN,NaN,NaN,NaN,NaN
2016,0.0,0,NaN,NaN,NaN,NaN,NaN
2017,18.010273,14,50.0,19.54708,-16.974184,-37.941994,0.474679
2018,26.550079,20,60.0,8.687259,-9.712128,-29.298206,0.906202
2019,-48.763142,4,50.0,4.560915,-28.942486,-57.884972,-0.842415
2020,38.94341,17,52.941176,23.418222,-21.477573,-80.02414,0.486646
2021,-41.29774,7,14.285714,19.281089,-10.096472,-50.178406,-0.823018
2022,72.058954,26,65.384615,10.027648,-10.934562,-44.984076,1.601877
2023,0.0,0,NaN,NaN,NaN,NaN,NaN
2024,0.0,0,NaN,NaN,NaN,NaN,NaN
Overall,65.501835,88.0,54.545455,13.556533,-14.630294,-173.172995,0.378245

In [859]:
tradebook_name_2 = f'{current_stock}_nxt50_fno_tb_ls_stonks.csv'
tb_pandas_per_month.to_csv(tradebook_name_2)

In [791]:
tb_pandas_per_month

,Stock Name,Trade Type,Entry Date,Entry Price,Exit Date,Exit Price,Points Captured,Qty,PnL,ROI%,Pct Change on Stock,Trade Year,Trade Number
11,ICICIGI,SHORT,2021-07-01,1478.45,2021-08-02,1596.75,-118.30,676.384051,-80016.233217,-8.001623,8.001623,2021,1S
12,ICICIGI,SHORT,2021-08-02,1596.75,2021-09-01,1595.10,1.65,676.384051,1116.033684,0.111603,-0.103335,2021,1S
13,ICICIGI,SHORT,2021-09-01,1595.10,2021-10-01,1485.75,109.35,676.384051,73962.595962,7.396260,-6.855370,2021,1S
14,ICICIGI,SHORT,2021-10-01,1485.75,2021-11-01,1441.15,44.60,676.384051,30166.728669,3.016673,-3.001851,2021,1S
15,ICICIGI,SHORT,2021-11-01,1441.15,2021-12-01,1404.40,36.75,676.384051,24857.113869,2.485711,-2.550047,2021,1S
16,ICICIGI,SHORT,2021-12-01,1404.40,2022-01-03,1374.35,30.05,676.384051,20325.340728,2.032534,-2.139704,2021,1S
17,ICICIGI,SHORT,2022-01-03,1374.35,2022-02-01,1263.40,110.95,676.384051,75044.810443,7.504481,-8.072907,2021,1S
18,ICICIGI,SHORT,2022-02-01,1263.40,2022-03-02,1334.25,-70.85,676.384051,-47921.810004,-4.792181,5.607883,2021,1S
19,ICICIGI,SHORT,2022-03-02,1334.25,2022-04-01,1286.95,47.30,676.384051,31992.965606,3.199297,-3.545063,2021,1S
20,ICICIGI,SHORT,2022-04-01,1286.95,2022-05-02,1266.70,20.25,676.384051,13696.777030,1.369678,-1.573488,2021,1S
21,ICICIGI,SHORT,2022-05-02,1266.70,2022-06-01,1124.25,142.45,676.384051,96350.908046,9.635091,-11.245757,2021,1S
22,ICICIGI,SHORT,2022-06-01,1124.25,2022-07-01,1226.30,-102.05,676.384051,-69024.992391,-6.902499,9.077163,2021,1S
23,ICICIGI,SHORT,2022-07-01,1226.30,2022-08-01,1292.45,-66.15,676.384051,-44742.804965,-4.474280,5.394275,2021,1S
24,ICICIGI,SHORT,2022-08-01,1292.45,2022-09-01,1154.30,138.15,676.384051,93442.456627,9.344246,-10.689002,2021,1S
25,ICICIGI,SHORT,2022-09-01,1154.30,2022-10-03,1176.70,-22.40,676.384051,-15151.002739,-1.515100,1.940570,2021,1S
26,ICICIGI,SHORT,2022-10-03,1176.70,2022-11-01,1217.95,-41.25,676.384051,-27900.842098,-2.790084,3.505566,2021,1S
27,ICICIGI,SHORT,2022-11-01,1217.95,2022-12-01,1245.65,-27.70,676.384051,-18735.838209,-1.873584,2.274313,2021,1S
28,ICICIGI,SHORT,2022-12-01,1245.65,2023-01-02,1139.60,106.05,676.384051,71730.528594,7.173053,-8.513627,2021,1S
29,ICICIGI,SHORT,2023-01-02,1139.60,2023-02-01,1106.35,33.25,676.384051,22489.769691,2.248977,-2.917690,2021,1S
30,ICICIGI,SHORT,2023-02-01,1106.35,2023-03-01,1077.20,29.15,676.384051,19716.595083,1.971660,-2.634790,2021,1S
31,ICICIGI,SHORT,2023-03-01,1077.20,2023-04-03,1086.75,-9.55,676.384051,-6459.467686,-0.645947,0.886558,2021,1S
32,ICICIGI,SHORT,2023-04-03,1086.75,2023-05-02,1190.80,-104.05,676.384051,-70377.760492,-7.037776,9.574419,2021,1S
33,ICICIGI,SHORT,2023-05-02,1190.80,2023-06-01,1351.50,-160.70,676.384051,-108694.916974,-10.869492,13.495129,2021,1S
0,ICICIGI,LONG,2023-06-01,1351.50,2023-07-03,1394.85,43.35,739.918609,32075.471698,3.207547,3.207547,2023,1L
1,ICICIGI,LONG,2023-07-03,1394.85,2023-08-01,1323.30,-71.55,739.918609,-52941.176471,-5.294118,-5.129584,2023,1L
2,ICICIGI,LONG,2023-08-01,1323.30,2023-09-01,1312.25,-11.05,739.918609,-8176.100629,-0.817610,-0.835034,2023,1L
3,ICICIGI,LONG,2023-09-01,1312.25,2023-10-03,1382.90,70.65,739.918609,52275.249723,5.227525,5.383883,2023,1L
4,ICICIGI,LONG,2023-10-03,1382.90,2023-11-01,1489.00,106.10,739.918609,78505.364410,7.850536,7.672283,2023,1L
5,ICICIGI,LONG,2023-11-01,1489.00,2023-12-01,1431.55,-57.45,739.918609,-42508.324084,-4.250832,-3.858294,2023,1L
6,ICICIGI,LONG,2023-12-01,1431.55,2024-01-01,1507.65,76.10,739.918609,56307.806141,5.630781,5.315916,2023,1L
7,ICICIGI,LONG,2024-01-01,1507.65,2024-02-01,1720.70,213.05,739.918609,157639.659637,15.763966,14.131264,2023,1L
8,ICICIGI,LONG,2024-02-01,1720.70,2024-03-01,1695.50,-25.20,739.918609,-18645.948946,-1.864595,-1.464520,2023,1L
9,ICICIGI,LONG,2024-03-01,1695.50,2024-04-01,1722.20,26.70,739.918609,19755.826859,1.975583,1.574757,2023,1L
10,ICICIGI,LONG,2024-04-01,1722.20,2024-05-02,1677.40,-44.80,739.918609,-33148.353681,-3.314835,-2.601324,2023,1L